"""Generate the golden_*.hpp headers from the C++ oracle.

Emits four committed C++ headers the Boost.UT tests assert against — this is
what pins the C++ core to the reference oracle. Regenerate (and commit) whenever
the metric, geometry, patch, or sweep math changes::

    uv run tests/cpp/gen_golden.py

  * golden_metric.hpp   — shape_2d value/grad/Hessian (cpp_core.metric_eval)
  * golden_metric_3d.hpp — mu_cond3 value/grad/Hessian (cpp_core.metric_eval_3d)
  * golden_geometry.hpp — project / tangent_space (cpp_core.geometry_project /
                           cpp_core.geometry_tangent)
  * golden_patch.hpp    — per-DOF patch_eval / energy+mindet / newton step
                           (cpp_core.patch_eval / cpp_core.energy_mindet /
                           cpp_core.newton_step)
  * golden_sweep.hpp    — colored GS barrier sweep (cpp_core.cpp_sweep)

Reference values are sourced from the C++ core via pybind oracle bindings.
Layout matches the C++ headers: vec(T) = [T00, T01, T10, T11]; A[:,k] =
s_k·(nbr_k − corner); T = A·W_inv. See src/metric.hpp, src/geometry.hpp,
src/patch.hpp, src/sweep.hpp.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from egg._cpp import cpp_core


def _fmt(x: float) -> str:
    return np.format_float_scientific(x, precision=17, unique=False, sign=True)


def _arr(vals) -> str:
    return "{" + ", ".join(_fmt(float(v)) for v in vals) + "}"


# ===========================================================================
# golden_metric.hpp — shape_2d value/grad/Hessian on curated T-matrices.
# ===========================================================================

def _rot(theta: float) -> np.ndarray:
    c, s = np.cos(theta), np.sin(theta)
    return np.array([[c, -s], [s, c]])


_METRIC_CASES: list[np.ndarray] = [
    np.array([[1.0, 0.0], [0.0, 1.0]]),       # identity
    np.array([[2.0, 0.0], [0.0, 2.0]]),       # uniform scale
    np.array([[1.5, 0.0], [0.0, 0.5]]),       # anisotropic scale
    _rot(0.6),                                  # pure rotation
    np.array([[1.0, 0.4], [0.0, 1.0]]),       # shear
    np.array([[1.2, -0.3], [0.5, 0.9]]),      # general
    _rot(2.3) @ np.diag([1.7, 0.6]),          # rotated anisotropic
    np.array([[1.0, 0.95], [0.95, 1.0]]),     # near-singular (det = 0.0975)
]


def gen_metric() -> str:
    rows: list[str] = []
    for T in _METRIC_CASES:
        t_flat = T.reshape(-1).astype(np.float64)  # [T00, T01, T10, T11]
        mu, grad, hess = cpp_core.metric_eval(t_flat)
        rows.append(
            "    {"
            f"\n      .t = {_arr(t_flat)},"
            f"\n      .mu = {_fmt(float(mu))},"
            f"\n      .grad = {_arr(grad)},"
            f"\n      .hess = {_arr(hess)}"
            "\n    }"
        )
    body = ",\n".join(rows)
    return f"""// GENERATED by tests/cpp/gen_golden.py — DO NOT EDIT BY HAND.
// Reference values from the C++ oracle (cpp_core.metric_eval).
// Regenerate: `uv run tests/cpp/gen_golden.py`.
#pragma once

#include <array>
#include <cstddef>

namespace egg::golden {{

struct Sample {{
  std::array<double, 4> t;      // vec(T) = [T00, T01, T10, T11]
  double mu;
  std::array<double, 4> grad;   // dmu/dvec(T)
  std::array<double, 16> hess;  // 4x4 row-major
}};

inline constexpr std::array<Sample, {len(_METRIC_CASES)}> kSamples = {{{{
{body}
}}}};

}}  // namespace egg::golden
"""


# ===========================================================================
# golden_metric_3d.hpp — mu_cond3 value/grad/Hessian on curated 3x3 T-matrices.
#
# Condition-number barrier mu_cond3(T) = |T|^2 |cof T|^2 / (9 det^2) - 1.
# Reference values from the closed-form C++ oracle (cpp_core.metric_eval_3d,
# i.e. mu_cond3_eval generated by scripts/derive_cond3.py). vec(T) is row-major
# [t00 t01 t02 t10 t11 t12 t20 t21 t22].
# ===========================================================================

def _rotz(theta: float) -> np.ndarray:
    c, s = np.cos(theta), np.sin(theta)
    return np.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])


def _rotx(theta: float) -> np.ndarray:
    c, s = np.cos(theta), np.sin(theta)
    return np.array([[1.0, 0.0, 0.0], [0.0, c, -s], [0.0, s, c]])


_METRIC_CASES_3D: list[np.ndarray] = [
    np.eye(3),                                          # identity (mu = 0)
    np.diag([2.0, 2.0, 2.0]),                           # uniform scale (mu = 0)
    np.diag([2.0, 0.5, 1.0]),                           # anisotropic stretch
    _rotz(0.6) @ _rotx(-0.4),                           # pure rotation (mu = 0)
    np.array([[1.0, 0.3, 0.0],                          # shear
              [0.0, 1.0, 0.2],
              [0.0, 0.0, 1.0]]),
    _rotz(1.1) @ np.diag([1.7, 0.6, 1.2]) @ _rotx(0.5),  # rotated anisotropic
    np.array([[1.2, -0.3, 0.1],                         # general well-conditioned
              [0.2, 0.9, -0.2],
              [0.05, 0.15, 1.1]]),
    np.array([[1.0, 0.0, 0.0],                          # near-singular (det small)
              [0.0, 1.0, 0.0],
              [0.0, 0.0, 0.05]]),
]


def gen_metric_3d() -> str:
    rows: list[str] = []
    for T in _METRIC_CASES_3D:
        t_flat = T.reshape(-1).astype(np.float64)  # row-major [t00..t22]
        mu, grad, hess = cpp_core.metric_eval_3d(t_flat)
        rows.append(
            "    {"
            f"\n      .t = {_arr(t_flat)},"
            f"\n      .mu = {_fmt(float(mu))},"
            f"\n      .grad = {_arr(grad)},"
            f"\n      .hess = {_arr(hess)}"
            "\n    }"
        )
    body = ",\n".join(rows)
    return f"""// GENERATED by tests/cpp/gen_golden.py — DO NOT EDIT BY HAND.
// Reference values from the C++ oracle (cpp_core.metric_eval_3d, i.e. the
// closed-form mu_cond3_eval generated by scripts/derive_cond3.py).
// Regenerate: `uv run tests/cpp/gen_golden.py`.
#pragma once

#include <array>
#include <cstddef>

namespace egg::golden {{

struct Sample3D {{
  std::array<double, 9> t;       // vec(T) row-major [t00..t22]
  double mu;
  std::array<double, 9> grad;    // dmu/dvec(T)
  std::array<double, 81> hess;   // 9x9 row-major, symmetric
}};

inline constexpr std::array<Sample3D, {len(_METRIC_CASES_3D)}> kSamples3D = {{{{
{body}
}}}};

}}  // namespace egg::golden
"""


# ===========================================================================
# golden_geometry.hpp — project / tangent_space per entity, curated points.
# ===========================================================================

def gen_geometry() -> str:
    # TAG_* constants and PARAM_PAD_SIZE live on the host-side encoding module.
    from egg.geometry.entity_encoding import (
        TAG_FREE, TAG_LINESEG, TAG_CIRCLE, TAG_ELLIPSE,
        PARAM_PAD_SIZE,
    )

    def pad(vals: list[float]) -> np.ndarray:
        p = np.zeros(PARAM_PAD_SIZE)
        p[: len(vals)] = vals
        return p

    # (name, tag, params, point) covering on-curve, off-curve, and degenerate
    # (p == center / zero-length) inputs per entity.
    line = pad([0.0, 0.0, 2.0, 1.0])        # start (0,0) -> end (2,1)
    circ = pad([0.5, -0.3, 2.0])             # center (0.5,-0.3), r=2
    elli = pad([0.0, 0.0, 3.0, 1.0])        # center (0,0), radii (3,1)

    # The 2D entity set is curves only; Sphere/Plane are 3D surfaces (milestone B).
    cases = [
        ("free", TAG_FREE, np.zeros(PARAM_PAD_SIZE), [0.3, -0.7]),
        ("lineseg-mid", TAG_LINESEG, line, [1.0, 1.5]),
        ("lineseg-before", TAG_LINESEG, line, [-1.0, -1.0]),   # clips to start
        ("lineseg-after", TAG_LINESEG, line, [5.0, 4.0]),      # clips to end
        ("circle-out", TAG_CIRCLE, circ, [3.0, 2.0]),
        ("circle-in", TAG_CIRCLE, circ, [0.6, -0.2]),
        ("circle-center", TAG_CIRCLE, circ, [0.5, -0.3]),      # p == center
        ("ellipse-out", TAG_ELLIPSE, elli, [2.0, 2.0]),
        ("ellipse-center", TAG_ELLIPSE, elli, [0.0, 0.0]),     # p == center
    ]

    rows: list[str] = []
    for _name, tag, params, p in cases:
        p_arr = np.asarray(p, dtype=np.float64)
        proj = np.asarray(cpp_core.geometry_project(p_arr, int(tag), params))
        tang = np.asarray(cpp_core.geometry_tangent(p_arr, int(tag), params)).reshape(-1)
        rows.append(
            "    {"
            f"\n      .tag = {int(tag)},"
            f"\n      .params = {_arr(params)},"
            f"\n      .p = {_arr(p_arr)},"
            f"\n      .proj = {_arr(proj)},"
            f"\n      .tang = {_arr(tang)}"
            "\n    }"
        )
    body = ",\n".join(rows)
    return f"""// GENERATED by tests/cpp/gen_golden.py — DO NOT EDIT BY HAND.
// Reference values from the C++ oracle (cpp_core.geometry_project /
// cpp_core.geometry_tangent). Regenerate: `uv run tests/cpp/gen_golden.py`.
#pragma once

#include <array>
#include <cstddef>

namespace egg::golden {{

struct GeoSample {{
  int tag;
  std::array<double, 12> params;  // PARAM_PAD_SIZE, zero-padded
  std::array<double, 2> p;        // query point (d = 2)
  std::array<double, 2> proj;     // project(p, tag, params)
  std::array<double, 2> tang;     // tangent_space(p, tag, params), (d,1) column
}};

inline constexpr std::array<GeoSample, {len(cases)}> kGeoSamples = {{{{
{body}
}}}};

}}  // namespace egg::golden
"""


# ===========================================================================
# golden_patch.hpp — per-DOF patch_eval / energy+mindet / newton step.
#
# Synthetic but structurally-valid patches: the moving DOF is node 0; each
# sample's three nodes are (corner, nbr0, nbr1) with the DOF occupying the slot
# its `role` selects. patch_eval only sums per-sample contributions, so parity
# holds for any valid arrays — these are built with a fixed RNG so det(A) > 0
# (finite mu, positive mindet) and the constrained `pos` lies near the entity.
# ===========================================================================

# C++ fixed capacities (must be >= the largest case here).
_MAXP = 8
_MAXNODES = 16


def _build_patch_case(P: int, tag: int, params: np.ndarray, roles, rng):
    """Construct one synthetic patch: returns the stencil arrays + pos + nodes."""
    from egg.smoothing.batch import make_chain_J

    # Node 0 is the moving DOF; the other two nodes of each sample are fresh.
    nodes = [np.array([0.0, 0.0])]  # placeholder for node 0, set below
    gc = np.zeros(P, dtype=np.int64)
    gn0 = np.zeros(P, dtype=np.int64)
    gn1 = np.zeros(P, dtype=np.int64)
    s0 = np.empty(P)
    s1 = np.empty(P)
    W_inv = np.empty((P, 2, 2))
    role = np.asarray(roles, dtype=np.int64)

    # A reasonable position for node 0 (the DOF); near the entity for tangents.
    if tag == 2:  # circle: place ~ on the circle
        c = params[:2]
        node0 = c + np.array([params[2], 0.0]) * 0.9
    elif tag == 1:  # lineseg: a point near the segment
        node0 = 0.5 * (params[:2] + params[2:4]) + np.array([0.1, -0.05])
    elif tag == 3:  # ellipse
        node0 = params[:2] + np.array([params[2], 0.0]) * 0.8
    else:
        node0 = np.array([0.4, -0.2])
    nodes[0] = node0

    for p in range(P):
        # corner / nbr0 / nbr1 geometry giving det(A) > 0 with s0=s1=1, W_inv≈I.
        base = node0 + 0.1 * rng.standard_normal(2)
        n0 = base + np.array([1.0, 0.0]) + 0.05 * rng.standard_normal(2)
        n1 = base + np.array([0.0, 1.0]) + 0.05 * rng.standard_normal(2)
        corner_pos, nbr0_pos, nbr1_pos = base, n0, n1
        r = role[p]
        # The DOF (node 0) takes the slot its role selects; others are fresh.
        if r == 0:
            gc[p] = 0
            corner_pos = node0
            gn0[p] = len(nodes); nodes.append(nbr0_pos)
            gn1[p] = len(nodes); nodes.append(nbr1_pos)
        elif r == 1:
            gn0[p] = 0
            nbr0_pos = node0
            gc[p] = len(nodes); nodes.append(corner_pos)
            gn1[p] = len(nodes); nodes.append(nbr1_pos)
        elif r == 2:
            gn1[p] = 0
            nbr1_pos = node0
            gc[p] = len(nodes); nodes.append(corner_pos)
            gn0[p] = len(nodes); nodes.append(nbr0_pos)
        else:  # absent (-1): all three nodes fresh
            gc[p] = len(nodes); nodes.append(corner_pos)
            gn0[p] = len(nodes); nodes.append(nbr0_pos)
            gn1[p] = len(nodes); nodes.append(nbr1_pos)
        # Re-derive positions so A is exactly s*(nbr - corner).
        s0[p] = 1.0 if rng.random() > 0.3 else -1.0
        s1[p] = 1.0 if rng.random() > 0.3 else -1.0
        # If a sign is negative, swap the nbr to the opposite side so det stays >0.
        if s0[p] < 0:
            off = nbr0_pos - corner_pos
            nbr0_pos = corner_pos - off
            if gn0[p] == 0:
                node0 = nbr0_pos  # keep node 0 consistent if it is the nbr
                nodes[0] = node0
            else:
                nodes[gn0[p]] = nbr0_pos
        if s1[p] < 0:
            off = nbr1_pos - corner_pos
            nbr1_pos = corner_pos - off
            if gn1[p] == 0:
                node0 = nbr1_pos
                nodes[0] = node0
            else:
                nodes[gn1[p]] = nbr1_pos
        # Mildly anisotropic W_inv (still keeps T well-conditioned).
        W_inv[p] = np.array([[1.0, 0.1], [0.0, 0.9]]) + 0.02 * rng.standard_normal((2, 2))

    X = np.array(nodes)
    J = make_chain_J(s0, s1, W_inv)
    pos = X[0].copy()
    return dict(X=X, gc=gc, gn0=gn0, gn1=gn1, s0=s0, s1=s1, W_inv=W_inv,
               role=role, J=J, tag=int(tag), params=params, pos=pos)


def gen_patch() -> str:
    # TAG_* constants and PARAM_PAD_SIZE live on the host-side encoding module.
    from egg.geometry.entity_encoding import (
        TAG_FREE, TAG_LINESEG, TAG_CIRCLE, PARAM_PAD_SIZE,
    )

    def pad(vals):
        q = np.zeros(PARAM_PAD_SIZE)
        q[: len(vals)] = vals
        return q

    rng = np.random.default_rng(20240601)
    specs = [
        # (tag, params, roles)
        (TAG_FREE, np.zeros(PARAM_PAD_SIZE), [0, 0, 0, 0]),
        (TAG_FREE, np.zeros(PARAM_PAD_SIZE), [0, 1, 2, 0, 1, 2]),  # mixed roles
        (TAG_FREE, np.zeros(PARAM_PAD_SIZE), [0, 1, -1, 2]),        # with absent
        (TAG_CIRCLE, pad([0.5, -0.3, 2.0]), [0, 0, 0, 0]),
        (TAG_LINESEG, pad([0.0, 0.0, 2.0, 1.0]), [0, 1, 2, 0]),
    ]

    cases = []
    for tag, params, roles in specs:
        c = _build_patch_case(len(roles), tag, params, roles, rng)
        X = np.ascontiguousarray(c["X"], dtype=np.float64)
        gc = np.ascontiguousarray(c["gc"], dtype=np.int32)
        gn0 = np.ascontiguousarray(c["gn0"], dtype=np.int32)
        gn1 = np.ascontiguousarray(c["gn1"], dtype=np.int32)
        s0 = np.ascontiguousarray(c["s0"], dtype=np.float64)
        s1 = np.ascontiguousarray(c["s1"], dtype=np.float64)
        W_inv = np.ascontiguousarray(c["W_inv"], dtype=np.float64)
        role = np.ascontiguousarray(c["role"], dtype=np.int32)
        J = np.ascontiguousarray(c["J"], dtype=np.float64)

        grad, hess, energy, mindet = cpp_core.patch_eval(
            X, gc, gn0, gn1, s0, s1, W_inv, role, J)
        e2, md2 = cpp_core.energy_mindet(X, gc, gn0, gn1, s0, s1, W_inv)
        delta = cpp_core.newton_step(
            np.asarray(grad), np.asarray(hess),
            np.ascontiguousarray(c["pos"], dtype=np.float64),
            int(c["tag"]),
            np.ascontiguousarray(c["params"], dtype=np.float64))
        c["expected"] = dict(
            grad=np.asarray(grad), hess=np.asarray(hess).reshape(-1),
            energy=float(energy), mindet=float(mindet),
            energy2=float(e2), mindet2=float(md2), delta=np.asarray(delta),
        )
        cases.append(c)

    def pad_to(a, n, fill=0):
        a = np.asarray(a).reshape(-1)
        out = np.full(n, fill, dtype=a.dtype if a.size else np.float64)
        out[: a.size] = a
        return out

    rows: list[str] = []
    for c in cases:
        P = len(c["role"])
        n_nodes = c["X"].shape[0]
        e = c["expected"]
        rows.append(
            "    {"
            f"\n      .n_nodes = {n_nodes},"
            f"\n      .X = {_arr(pad_to(c['X'].reshape(-1), _MAXNODES * 2))},"
            f"\n      .P = {P},"
            f"\n      .gc = {{{', '.join(str(int(v)) for v in pad_to(c['gc'], _MAXP))}}},"
            f"\n      .gn0 = {{{', '.join(str(int(v)) for v in pad_to(c['gn0'], _MAXP))}}},"
            f"\n      .gn1 = {{{', '.join(str(int(v)) for v in pad_to(c['gn1'], _MAXP))}}},"
            f"\n      .s0 = {_arr(pad_to(c['s0'], _MAXP))},"
            f"\n      .s1 = {_arr(pad_to(c['s1'], _MAXP))},"
            f"\n      .W_inv = {_arr(pad_to(c['W_inv'].reshape(-1), _MAXP * 4))},"
            f"\n      .role = {{{', '.join(str(int(v)) for v in pad_to(c['role'], _MAXP, -1))}}},"
            f"\n      .J = {_arr(pad_to(c['J'].reshape(-1), _MAXP * 24))},"
            f"\n      .tag = {int(c['tag'])},"
            f"\n      .params = {_arr(c['params'])},"
            f"\n      .grad = {_arr(e['grad'])},"
            f"\n      .hess = {_arr(e['hess'])},"
            f"\n      .energy = {_fmt(e['energy'])},"
            f"\n      .mindet = {_fmt(e['mindet'])},"
            f"\n      .delta = {_arr(e['delta'])}"
            "\n    }"
        )
    body = ",\n".join(rows)
    return f"""// GENERATED by tests/cpp/gen_golden.py — DO NOT EDIT BY HAND.
// Reference values from the C++ oracle (cpp_core.patch_eval,
// cpp_core.energy_mindet, cpp_core.newton_step) on synthetic valid patches.
// Regenerate: `uv run tests/cpp/gen_golden.py`.
#pragma once

#include <array>
#include <cstddef>

namespace egg::golden {{

inline constexpr int kMaxP = {_MAXP};
inline constexpr int kMaxNodes = {_MAXNODES};

struct PatchSample {{
  int n_nodes;                          // valid node count (X has 2*n_nodes)
  std::array<double, {_MAXNODES} * 2> X;  // flat positions [x0,y0,x1,y1,...]
  int P;                                // valid sample count
  std::array<int, {_MAXP}> gc;
  std::array<int, {_MAXP}> gn0;
  std::array<int, {_MAXP}> gn1;
  std::array<double, {_MAXP}> s0;
  std::array<double, {_MAXP}> s1;
  std::array<double, {_MAXP} * 4> W_inv;  // P x (2x2) row-major
  std::array<int, {_MAXP}> role;
  std::array<double, {_MAXP} * 24> J;     // P x (4x6) row-major
  int tag;
  std::array<double, 12> params;
  // expected (oracle):
  std::array<double, 2> grad;
  std::array<double, 4> hess;           // 2x2 row-major
  double energy;
  double mindet;
  std::array<double, 2> delta;          // newton step from cpp_core.newton_step
}};

inline constexpr std::array<PatchSample, {len(cases)}> kPatchSamples = {{{{
{body}
}}}};

}}  // namespace egg::golden
"""


# ===========================================================================
# golden_sweep.hpp — colored Gauss-Seidel sweep on a mini-grid.
#
# Builds a small 4x4 grid using TopologyBuilder, runs a few sweeps using the
# C++ backend (CppSweepSession), and dumps the initial X, group batches, energy
# stencil, and per-sweep (energy, mindet, final X) for the C++ sweep test.
# ===========================================================================

_MAXP_SWEEP = 20  # max P in the mini-grid (demo grids use P ∈ {8,16,20})
_MAX_DOF_PER_GROUP = 32  # max DOFs per (colour,P) group in the mini-grid


def gen_sweep() -> str:
    from egg.smoothing.solver import build_sweep_context
    from egg.smoothing.targets import IdentityTarget
    from egg.topology.builder import TopologyBuilder
    from egg.smoothing.cpp_backend import (
        _ensure_group_batches, CppSweepSession,
    )

    # Build a small 4x4 grid
    builder = TopologyBuilder(d=2)
    for name, pos in [("A", (0.0, 0.0)), ("B", (4.0, 0.0)),
                      ("C", (4.0, 4.0)), ("D", (0.0, 4.0))]:
        builder.add_corner(name, pos, fixed=True)
    builder.add_block("main", ("A", "D", "B", "C"), (4, 4))
    topo = builder.build()
    topo.initialize_grid()
    grid = topo.grid

    target = IdentityTarget(d=2)

    # Mixed-tag sliding constraints on free edge DOFs (Phase 1a): inject a few
    # fixed-size entities (no arena) so the device sweep exercises non-Free
    # partition kernels — LineSegment, Circle, and CircleArc (a trimmed
    # analytic). Geometry is chosen so each constrained DOF starts ON its entity
    # (the 0.05 perturbation below stays well-posed, det(A)>0). DOFs are looked
    # up by position before the perturbation; they remain in free_mask (sliding).
    from egg.geometry.analytic2d import Circle, LineSegment
    from egg.geometry.curves2d import BSplineCurve, CircleArc, CompositePath

    def gidx_at(x: float, y: float) -> int:
        matches = np.where(
            (np.abs(grid.global_nodes[:, 0] - x) < 1e-9) &
            (np.abs(grid.global_nodes[:, 1] - y) < 1e-9)
        )[0]
        assert len(matches) == 1, f"expected one DOF at ({x},{y}), got {len(matches)}"
        return int(matches[0])

    # Bottom edge: two DOFs slide on a horizontal segment y=0, x in [1,3].
    seg = LineSegment(start=(1.0, 0.0), end=(3.0, 0.0))
    grid.dof_constraints[gidx_at(1.0, 0.0)] = seg
    grid.dof_constraints[gidx_at(3.0, 0.0)] = seg
    # A circle centred at (2,2) radius 2 passes through (2,0) and (0,2);
    # constrain those two edge midpoints to slide on it.
    circ = Circle(center=(2.0, 2.0), radius=2.0)
    grid.dof_constraints[gidx_at(2.0, 0.0)] = circ
    grid.dof_constraints[gidx_at(0.0, 2.0)] = circ
    # Rounded top-right corner: a quarter arc of radius 1 about (4,4) from
    # angle pi (point (3,4)) to 3pi/2 (point (4,3)).
    arc = CircleArc(center=(4.0, 4.0), radius=1.0, t0=np.pi, t1=1.5 * np.pi)
    grid.dof_constraints[gidx_at(3.0, 4.0)] = arc
    grid.dof_constraints[gidx_at(4.0, 3.0)] = arc
    # A degree-2 B-spline arch over the top edge: control points (1, 3.8),
    # (2, 4.2), (3, 3.8) with clamped knots [0,0,0,1,1,1] — the midpoint
    # at t=0.5 is exactly (2, 4.0), matching the grid node. Exercises the
    # B-spline partition kernel's runtime numerics (find_span + basis_ders
    # + seeded-Newton projection) on device. Phase 2-A gates this via the
    # blob path (arena-carried knots/ctrl); Phase 2-B switches to SoA.
    spline = BSplineCurve(degree=2, knots=[0.0, 0.0, 0.0, 1.0, 1.0, 1.0],
                          ctrl=[[1.0, 3.8], [2.0, 4.2], [3.0, 3.8]])
    grid.dof_constraints[gidx_at(2.0, 4.0)] = spline
    # A 2-segment composite (polyline) up the left edge: (0,0)->(0,2)->(0,4).
    # DOFs at (0,1) and (0,3) slide on it (each starts exactly on its segment).
    # Exercises the composite partition kernel's SoA load + per-segment
    # dispatch_entity_type projection on device (Phase 3) — fixed-size segments.
    poly = CompositePath([
        LineSegment(start=(0.0, 0.0), end=(0.0, 2.0)),
        LineSegment(start=(0.0, 2.0), end=(0.0, 4.0)),
    ])
    grid.dof_constraints[gidx_at(0.0, 1.0)] = poly
    grid.dof_constraints[gidx_at(0.0, 3.0)] = poly

    ctx = build_sweep_context(grid, target)

    # Perturb initial positions slightly
    rng = np.random.default_rng(20240615)
    grid.global_nodes[:] += 0.05 * rng.standard_normal(grid.global_nodes.shape)

    X0 = grid.global_nodes.copy()
    num_nodes = X0.shape[0]

    # Populate group batches (needed for header data and for the C++ session).
    _ensure_group_batches(ctx)

    # Run sweep-by-sweep via the C++ backend to capture per-sweep data.
    session = CppSweepSession(ctx, X0, device="cpu")
    energies = []
    mindets = []
    for _s in range(3):
        e_arr, m_arr = session.run(1)
        energies.append(float(np.asarray(e_arr)[0]))
        mindets.append(float(np.asarray(m_arr)[0]))
    X_final = session.get_X()

    energies = np.array(energies)
    mindets = np.array(mindets)

    # Extract group data
    groups_data = []
    for colour in range(ctx.num_colours):
        for P, dofs in ctx.get_colour_P_groups(colour).items():
            b = ctx.jax_group_batches[(colour, P)]
            groups_data.append({
                "P": P,
                "D": len(dofs),
                "gc": np.asarray(b["gc"]),
                "gn0": np.asarray(b["gn0"]),
                "gn1": np.asarray(b["gn1"]),
                "s0": np.asarray(b["s0"]),
                "s1": np.asarray(b["s1"]),
                "W_inv": np.asarray(b["W_inv"]),
                "role": np.asarray(b["role"]),
                "J": np.asarray(b["J"]),
                "dof_idx": np.asarray(b["dof_idx"]),
                "tag": np.asarray(b["tag"]),
                "params": np.asarray(b["params"]),
            })

    es_data = {k: np.asarray(ctx.energy_stencil[k]) for k in
               ("gc", "gn0", "gn1", "s0", "s1", "W_inv")}

    # Variable-length entity data (B-spline knots/nets). Shared across all
    # groups — the arena offsets in params index into this single flat array.
    # Empty when only fixed-size entities are present.
    arena_data = np.asarray(ctx.entity_arena, dtype=np.float64) if ctx.entity_arena is not None else np.empty(0, dtype=np.float64)
    arena_size = int(arena_data.shape[0])

    # Generate C++ header
    def pad_to(a, n, fill=0):
        a = np.asarray(a).reshape(-1)
        out = np.full(n, fill, dtype=a.dtype if a.size else np.float64)
        out[: a.size] = a
        return out

    # Format group arrays
    def _arr_int(vals, n, fill=0):
        """Format an integer array as C++ initializer list."""
        padded = pad_to(vals, n, fill)
        return "{" + ", ".join(str(int(v)) for v in padded) + "}"

    group_strs = []
    for g in groups_data:
        P = g["P"]
        D = g["D"]
        group_strs.append(
            "    {"
            f"\n      .P = {P},"
            f"\n      .D = {D},"
            f"\n      .gc = {_arr_int(g['gc'].reshape(-1), _MAXP_SWEEP * _MAX_DOF_PER_GROUP)},"
            f"\n      .gn0 = {_arr_int(g['gn0'].reshape(-1), _MAXP_SWEEP * _MAX_DOF_PER_GROUP)},"
            f"\n      .gn1 = {_arr_int(g['gn1'].reshape(-1), _MAXP_SWEEP * _MAX_DOF_PER_GROUP)},"
            f"\n      .s0 = {_arr(pad_to(g['s0'].reshape(-1), _MAXP_SWEEP * _MAX_DOF_PER_GROUP))},"
            f"\n      .s1 = {_arr(pad_to(g['s1'].reshape(-1), _MAXP_SWEEP * _MAX_DOF_PER_GROUP))},"
            f"\n      .W_inv = {_arr(pad_to(g['W_inv'].reshape(-1), _MAXP_SWEEP * _MAX_DOF_PER_GROUP * 4))},"
            f"\n      .role = {_arr_int(g['role'].reshape(-1), _MAXP_SWEEP * _MAX_DOF_PER_GROUP, -1)},"
            f"\n      .J = {_arr(pad_to(g['J'].reshape(-1), _MAXP_SWEEP * _MAX_DOF_PER_GROUP * 24))},"
            f"\n      .dof_idx = {_arr_int(g['dof_idx'], _MAX_DOF_PER_GROUP)},"
            f"\n      .tag = {_arr_int(g['tag'], _MAX_DOF_PER_GROUP)},"
            f"\n      .params = {_arr(pad_to(g['params'].reshape(-1), _MAX_DOF_PER_GROUP * 12))}"
            "\n    }"
        )
    groups_body = ",\n".join(group_strs)

    # Energy stencil
    es_num = es_data["gc"].shape[0]
    es_str = (
        "  {"
        f"\n    .gc = {_arr_int(es_data['gc'].reshape(-1), es_num)},"
        f"\n    .gn0 = {_arr_int(es_data['gn0'].reshape(-1), es_num)},"
        f"\n    .gn1 = {_arr_int(es_data['gn1'].reshape(-1), es_num)},"
        f"\n    .s0 = {_arr(es_data['s0'])},"
        f"\n    .s1 = {_arr(es_data['s1'])},"
        f"\n    .W_inv = {_arr(es_data['W_inv'].reshape(-1))}"
        "\n  }"
    )

    return f"""// GENERATED by tests/cpp/gen_golden.py — DO NOT EDIT BY HAND.
// Reference values from the C++ backend (CppSweepSession) on a mini 4x4 grid.
// Regenerate: `uv run tests/cpp/gen_golden.py`.
#pragma once

#include <array>
#include <cstddef>

namespace egg::golden {{

inline constexpr int kMaxPSweep = {_MAXP_SWEEP};
inline constexpr int kMaxDofPerGroup = {_MAX_DOF_PER_GROUP};
inline constexpr int kNumGroups = {len(groups_data)};
inline constexpr int kNumNodes = {num_nodes};
inline constexpr int kNumSweeps = 3;
inline constexpr int kEnergyStencilSize = {es_num};
inline constexpr int kArenaSize = {arena_size};

struct SweepGroup {{
  int P;
  std::size_t D;
  std::array<int, {_MAXP_SWEEP * _MAX_DOF_PER_GROUP}> gc;
  std::array<int, {_MAXP_SWEEP * _MAX_DOF_PER_GROUP}> gn0;
  std::array<int, {_MAXP_SWEEP * _MAX_DOF_PER_GROUP}> gn1;
  std::array<double, {_MAXP_SWEEP * _MAX_DOF_PER_GROUP}> s0;
  std::array<double, {_MAXP_SWEEP * _MAX_DOF_PER_GROUP}> s1;
  std::array<double, {_MAXP_SWEEP * _MAX_DOF_PER_GROUP * 4}> W_inv;
  std::array<int, {_MAXP_SWEEP * _MAX_DOF_PER_GROUP}> role;
  std::array<double, {_MAXP_SWEEP * _MAX_DOF_PER_GROUP * 24}> J;
  std::array<int, {_MAX_DOF_PER_GROUP}> dof_idx;
  std::array<int, {_MAX_DOF_PER_GROUP}> tag;
  std::array<double, {_MAX_DOF_PER_GROUP * 12}> params;
}};

struct SweepEnergyStencil {{
  static constexpr std::size_t num_samples = {es_num};
  std::array<int, num_samples> gc;
  std::array<int, num_samples> gn0;
  std::array<int, num_samples> gn1;
  std::array<double, num_samples> s0;
  std::array<double, num_samples> s1;
  std::array<double, num_samples * 4> W_inv;
}};

inline constexpr std::array<SweepGroup, {len(groups_data)}> kSweepGroups = {{{{
{groups_body}
}}}};

inline constexpr SweepEnergyStencil kEnergyStencil = {es_str};

inline constexpr std::array<double, {num_nodes * 2}> kX0 = {_arr(X0.reshape(-1))};

inline constexpr std::array<double, {num_nodes * 2}> kXFinal = {_arr(X_final.reshape(-1))};

inline constexpr std::array<double, 3> kEnergies = {_arr(energies)};

inline constexpr std::array<double, 3> kMindets = {_arr(mindets)};

inline constexpr std::array<double, kArenaSize> kArena = {_arr(arena_data)};

}}  // namespace egg::golden
"""


def main() -> None:
    here = Path(__file__).parent
    for name, gen in (("golden_metric.hpp", gen_metric),
                      ("golden_metric_3d.hpp", gen_metric_3d),
                      ("golden_geometry.hpp", gen_geometry),
                      ("golden_patch.hpp", gen_patch),
                      ("golden_sweep.hpp", gen_sweep)):
        dest = here / name
        dest.write_text(gen())
        print(f"wrote {dest}")


if __name__ == "__main__":
    main()
