// the 2D shape_2d metric mu(T) = |T|^2 / (2 det T) - 1, with both
// a closed-form value/grad/Hess (the in-kernel production path) and dual-AD
// value/grad/Hess (the de-risking parity path). Mirrors the NumPy oracle in
// egg.smoothing.metrics (_shape2d_value / _shape2d_value_grad /
// _shape2d_hess_T) exactly; vec(T) = [a, b, c, d] = [T00, T01, T10, T11].
//
// 3D mu_cond3 has a closed-form value/grad/Hess path too
// (mu_cond3_eval below) generated by scripts/derive_cond3.py. Same MIRROR
// discipline: regenerate the body via the script if the metric math changes,
// and verify parity against the Dual2<9> AD path (tests/cpp/test_metric_3d.cpp).
#pragma once

#include "core.hpp"
#include "dual.hpp"

#include <array>
#include <cmath>
#include <concepts>
#include <string_view>
#include <variant>

namespace egg
{

// Flattened vec(T)-space shapes. The un-suffixed names are the D=2 aliases the
// closed-form 2D metric and the oracle surface use; VecTN/GradN/HessN<D> from
// core.hpp are the generic shapes the templated objectives are written over.
using VecT = VecTN<2>;  // [a, b, c, d] for d=2
using Grad = GradN<2>;  // dmu/dvec(T)
using Hess = HessN<2>;  // (d²)×(d²) row-major; 4×4 for d=2

// The shape_2d barrier μ = |T|²/(2 det T) − 1 and its closed-form grad/Hess are
// the 2D metric; a 3D core supplies a 3D barrier (e.g. the condition-number form)
// — most cleanly via dual.hpp AD over an N-generic μ.

// --- generic scalar metric, reused for double / Dual<4> / Dual2<4> ---
//
//   D  = a*d - b*c
//   s  = a^2 + b^2 + c^2 + d^2
//   mu = s / (2 D) - 1
template <typename T> constexpr T mu_shape2d(const T& a, const T& b, const T& c, const T& d)
{
    const T D = a * d - b * c;
    const T s = a * a + b * b + c * c + d * d;
    return s / (2.0 * D) - 1.0;
}

inline double mu_value(const VecT& t) { return mu_shape2d(t[0], t[1], t[2], t[3]); }

// --- closed-form gradient (matches _shape2d_value_grad) ---
inline Grad mu_grad_closedform(const VecT& t)
{
    const double a = t[0], b = t[1], c = t[2], d = t[3];
    const double D = (a * d) - (b * c);
    const double s = (a * a) + (b * b) + (c * c) + (d * d);
    const double coef = s / (2.0 * D * D);
    return Grad {(a / D) - (coef * d),
                 (b / D) + (coef * c),
                 (c / D) + (coef * b),
                 (d / D) - (coef * a)};
}

// d vec(C)/d vec(T) with cofactor vec(C) = [d, -c, -b, a].
// MIRROR: keep in sync with egg.smoothing.metrics._HESS_P and
// egg.smoothing.batch._HESS_P (Python). Cross-language, so unavoidable; any
// change must be applied to all three copies.
inline constexpr std::array<double, kVecT * kVecT> kHessP = {0.0,
                                                             0.0,
                                                             0.0,
                                                             1.0,  //
                                                             0.0,
                                                             0.0,
                                                             -1.0,
                                                             0.0,  //
                                                             0.0,
                                                             -1.0,
                                                             0.0,
                                                             0.0,  //
                                                             1.0,
                                                             0.0,
                                                             0.0,
                                                             0.0};

// --- closed-form Hessian (matches _shape2d_hess_T) ---
//   H = (1/D) I
//       - (1/D^2) (t cof^T + cof t^T)
//       + (s/D^3) cof cof^T
//       - (s/(2 D^2)) P
inline Hess mu_hess_closedform(const VecT& t)
{
    const double a = t[0], b = t[1], c = t[2], d = t[3];
    const double D = (a * d) - (b * c);
    const double s = (a * a) + (b * b) + (c * c) + (d * d);
    const std::array<double, kVecT> tv {a, b, c, d};
    const std::array<double, kVecT> cof {d, -c, -b, a};
    const double invD = 1.0 / D;
    const double invD2 = 1.0 / (D * D);
    const double sD3 = s / (D * D * D);
    const double s2D2 = s / (2.0 * D * D);
    Hess H {};
    for (int i = 0; i < kVecT; ++i) {
        for (int j = 0; j < kVecT; ++j) {
            const double eye = (i == j) ? 1.0 : 0.0;
            H[(i * kVecT) + j] = (invD * eye) - (invD2 * ((tv[i] * cof[j]) + (cof[i] * tv[j]))) +
                                 (cof[i] * sD3 * cof[j]) - (s2D2 * kHessP[(i * kVecT) + j]);
        }
    }
    return H;
}

// --- dual-AD gradient (forward mode, one pass with all 4 seeds) ---
inline Grad mu_grad_dual(const VecT& t)
{
    using Dv = Dual<kVecT>;  // AD over the kVecT components of vec(T)
    const Dv r = mu_shape2d(seed_dual<kVecT>(t[0], 0),
                            seed_dual<kVecT>(t[1], 1),
                            seed_dual<kVecT>(t[2], 2),
                            seed_dual<kVecT>(t[3], 3));
    return Grad {r.g[0], r.g[1], r.g[2], r.g[3]};
}

// --- dual-AD Hessian (second-order forward, one pass) ---
inline Hess mu_hess_dual(const VecT& t)
{
    using Dv = Dual2<kVecT>;
    const Dv r = mu_shape2d(seed_dual2<kVecT>(t[0], 0),
                            seed_dual2<kVecT>(t[1], 1),
                            seed_dual2<kVecT>(t[2], 2),
                            seed_dual2<kVecT>(t[3], 3));
    Hess H {};
    for (int i = 0; i < kVecT; ++i) {
        for (int j = 0; j < kVecT; ++j) { H[(i * kVecT) + j] = r.h[i][j]; }
    }
    return H;
}

// ---------------------------------------------------------------------------
// δ-continuation untangle surrogate (mirrors metrics._untangle_surrogate):
//   Dh(δ) = ½(D + √(D² + 4δ²))   (> 0 everywhere; → D as δ → 0 for D > 0)
//   μ_δ   = s / (2·Dh) − 1
// Generic over double / Dual<4> / Dual2<4> so value, grad, and Hessian all come
// from the one definition (closed form for value, dual-AD for the derivatives).
// ---------------------------------------------------------------------------
template <typename T>
inline T mu_untangle(const T& a, const T& b, const T& c, const T& d, double delta)
{
    using std::sqrt;  // egg::sqrt for Dual/Dual2 (ADL); std::sqrt for double
    const T D = a * d - b * c;
    const T s = a * a + b * b + c * c + d * d;
    const T disc = D * D + T(4.0 * delta * delta);
    const T Dh = 0.5 * (D + sqrt(disc));
    return s / (2.0 * Dh) - 1.0;
}

// ---------------------------------------------------------------------------
// 3D condition-number barrier (generic over double / Dual<9> / Dual2<9>):
//   μ_cond = |T|²·|T⁻¹|²/d² − 1 = (Σ tᵢ²)(Σ cof(T)ᵢ²) / (9 det²) − 1
// Rational in the entries of T (no fractional powers), so closed form and
// dual-AD are clean and device-friendly. vec(T) is row-major
// [t00 t01 t02 t10 ... t22]. Sanity: at d=2 the cofactor norm equals |T|², so
// the same formula collapses to s²/(4 det²) − 1 (the Python `_shape_value`).
// ---------------------------------------------------------------------------
template <typename T> constexpr T det3(const std::array<T, 9>& t)
{
    return (t[0] * ((t[4] * t[8]) - (t[5] * t[7]))) - (t[1] * ((t[3] * t[8]) - (t[5] * t[6]))) +
           (t[2] * ((t[3] * t[7]) - (t[4] * t[6])));
}

// The 9 cofactors of the 3×3 (row-major; adj = cof^T).
template <typename T> constexpr std::array<T, 9> cof3(const std::array<T, 9>& t)
{
    return {(t[4] * t[8]) - (t[5] * t[7]),
            -((t[3] * t[8]) - (t[5] * t[6])),
            (t[3] * t[7]) - (t[4] * t[6]),
            -((t[1] * t[8]) - (t[2] * t[7])),
            (t[0] * t[8]) - (t[2] * t[6]),
            -((t[0] * t[7]) - (t[1] * t[6])),
            (t[1] * t[5]) - (t[2] * t[4]),
            -((t[0] * t[5]) - (t[2] * t[3])),
            (t[0] * t[4]) - (t[1] * t[3])};
}

template <typename T> constexpr T mu_cond3(const std::array<T, 9>& t)
{
    const T D = det3(t);
    const std::array<T, 9> cof = cof3(t);
    T s = T(0.0);
    T q = T(0.0);
    for (int i = 0; i < 9; ++i) {
        s = s + (t[i] * t[i]);
        q = q + (cof[i] * cof[i]);
    }
    return (s * q) / (9.0 * D * D) - 1.0;
}

// δ-continuation untangle surrogate: det → Dh = ½(det + √(det² + 4δ²)) (> 0 on
// folded cells), mirroring the 2D mu_untangle substitution.
template <typename T> inline T mu_cond3_untangle(const std::array<T, 9>& t, double delta)
{
    using std::sqrt;  // egg::sqrt for Dual/Dual2 (ADL); std::sqrt for double
    const T D = det3(t);
    const T disc = (D * D) + T(4.0 * delta * delta);
    const T Dh = 0.5 * (D + sqrt(disc));
    const std::array<T, 9> cof = cof3(t);
    T s = T(0.0);
    T q = T(0.0);
    for (int i = 0; i < 9; ++i) {
        s = s + (t[i] * t[i]);
        q = q + (cof[i] * cof[i]);
    }
    return (s * q) / (9.0 * Dh * Dh) - 1.0;
}

// --- closed-form mu_cond3 value/grad/Hess (production path for D=3) ---
// Generated by scripts/derive_cond3.py (SymPy + CSE + GPU power printer +
// D-power division peephole). Replaces the Dual2<9> AD on the GPU hot path
// to remove the 729-double AD state that was clamping VGPRs to 256 and
// spilling 23 KB of scratch (see rocprof trace for sweep_colour_kernel<3>).
// Numerical parity vs Dual2<9> AD verified to ~1e-14 (test_metric_3d.cpp).
//
// The Dual2<9> AD path remains in mu_cond3/det3/cof3 templates as the
// parity reference and the basis for UntangleObjectiveT<3> (whose
// δ-surrogate has a sqrt and is messier to close-form).
struct MuCond3Eval {
    double val;
    double grad[9];
    double hess[81];  // 9x9 row-major, symmetric
};

__attribute__((noinline)) inline MuCond3Eval mu_cond3_eval(const double* t)
{
    MuCond3Eval r;
    // --- Common Subexpressions (SymPy CSE) ---
    const double x0 = ((t[0] * t[0]));
    const double x1 = ((t[1] * t[1]));
    const double x2 = ((t[2] * t[2]));
    const double x3 = ((t[3] * t[3]));
    const double x4 = ((t[4] * t[4]));
    const double x5 = ((t[5] * t[5]));
    const double x6 = ((t[6] * t[6]));
    const double x7 = ((t[7] * t[7]));
    const double x8 = ((t[8] * t[8]));
    const double x9 = x0 + x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8;
    const double x10 = t[4] * t[8];
    const double x11 = t[5] * t[7];
    const double x12 = x10 - x11;
    const double x13 = t[3] * t[7];
    const double x14 = t[4] * t[6];
    const double x15 = x13 - x14;
    const double x16 = t[3] * t[8];
    const double x17 = t[5] * t[6];
    const double x18 = x16 - x17;
    const double x19 = t[0] * x12 - t[1] * x18 + t[2] * x15;
    const double x20 = (1.0 / (x19 * x19));
    const double x21 = t[0] * t[4];
    const double x22 = t[1] * t[3];
    const double x23 = x21 - x22;
    const double x24 = t[0] * t[5];
    const double x25 = t[2] * t[3] - x24;
    const double x26 = t[0] * t[7];
    const double x27 = t[1] * t[6] - x26;
    const double x28 = t[0] * t[8];
    const double x29 = t[2] * t[6];
    const double x30 = x28 - x29;
    const double x31 = t[1] * t[5];
    const double x32 = t[2] * t[4];
    const double x33 = x31 - x32;
    const double x34 = t[1] * t[8];
    const double x35 = t[2] * t[7] - x34;
    const double x36 = -x18;
    const double x37 = ((x12 * x12)) + ((x15 * x15)) + ((x23 * x23)) + ((x25 * x25)) +
                       ((x27 * x27)) + ((x30 * x30)) + ((x33 * x33)) + ((x35 * x35)) +
                       ((x36 * x36));
    const double x38 = 2 * x23;
    const double x39 = 2 * t[5];
    const double x40 = 2 * x27;
    const double x41 = 2 * t[8];
    const double x42 = t[4] * x38 - t[7] * x40 - x25 * x39 + x30 * x41;
    const double x43 = (1.0 / 9.0) * x9;
    const double x44 = x20 * x43;
    const double x45 = (2.0 / 9.0) * x20 * x37;
    const double inv_x19 = x20 * x19;  // 1/D
    const double x46 = x20 * inv_x19;
    const double x47 = 2 * x10;
    const double x48 = -2 * x11;
    const double x49 = -x47 - x48;
    const double x50 = x46 * x49;
    const double x51 = x37 * x43;
    const double x52 = -t[3] * x38 + 2 * t[5] * x33 + 2 * t[6] * x27 - x35 * x41;
    const double x53 = 2 * x16;
    const double x54 = -2 * x17;
    const double x55 = x53 + x54;
    const double x56 = x46 * x51;
    const double x57 = 2 * x25;
    const double x58 = 2 * x33;
    const double x59 = 2 * t[6];
    const double x60 = 2 * t[7];
    const double x61 = t[3] * x57 - t[4] * x58 - x30 * x59 + x35 * x60;
    const double x62 = 2 * x13;
    const double x63 = -2 * x14;
    const double x64 = -x62 - x63;
    const double x65 = -t[1] * x38 + 2 * t[2] * x25 + 2 * t[7] * x15 - x36 * x41;
    const double x66 = 2 * x34;
    const double x67 = t[2] * t[7];
    const double x68 = -2 * x67;
    const double x69 = x66 + x68;
    const double x70 = t[0] * x38 - t[2] * x58 + x12 * x41 - x15 * x59;
    const double x71 = 2 * x28;
    const double x72 = -2 * x29;
    const double x73 = -x71 - x72;
    const double x74 = -t[0] * x57 + 2 * t[1] * x33 + 2 * t[6] * x36 - x12 * x60;
    const double x75 = 2 * x26;
    const double x76 = t[1] * t[6];
    const double x77 = -2 * x76;
    const double x78 = x75 + x77;
    const double x79 = 2 * t[2];
    const double x80 = t[1] * x40 - 2 * t[4] * x15 - x30 * x79 + x36 * x39;
    const double x81 = 2 * x31;
    const double x82 = -2 * x32;
    const double x83 = -x81 - x82;
    const double x84 = -t[0] * x40 + 2 * t[2] * x35 + 2 * t[3] * x15 - x12 * x39;
    const double x85 = 2 * x24;
    const double x86 = t[2] * t[3];
    const double x87 = -2 * x86;
    const double x88 = x85 + x87;
    const double x89 = 2 * t[1];
    const double x90 = 2 * t[3];
    const double x91 = 2 * t[0] * x30 + 2 * t[4] * x12 - x35 * x89 - x36 * x90;
    const double x92 = 2 * x21;
    const double x93 = -2 * x22;
    const double x94 = -x92 - x93;
    const double x95 = t[0] * x20;
    const double x96 = 2 * x5;
    const double x97 = 2 * x8;
    const double x98 = x96 + x97;
    const double x99 = 2 * x4;
    const double x100 = 2 * x7;
    const double x101 = x100 + x99;
    const double x102 = (2.0 / 9.0) * x42;
    const double x103 = t[0] * x37;
    const double x104 = x51 * x20 * x20;
    const double x105 = x104 * x49;
    const double x106 = t[4] * x90;
    const double x107 = t[7] * x59;
    const double x108 = (2.0 / 9.0) * x95;
    const double x109 = t[1] * x20;
    const double x110 = x46 * x55;
    const double x111 = x42 * x43;
    const double x112 = x43 * x50;
    const double x113 = (2.0 / 9.0) * x103;
    const double x114 = (2.0 / 9.0) * x37;
    const double x115 = x114 * x50;
    const double x116 = 3 * x16 - 3 * x17;
    const double x117 = t[3] * x39;
    const double x118 = t[6] * x41;
    const double x119 = x102 * x20;
    const double x120 = x46 * x64;
    const double x121 = 3 * t[4] * t[6] - 3 * x13;
    const double x122 = t[4] * x89;
    const double x123 = t[2] * x39;
    const double x124 = x46 * x69;
    const double x125 = 3 * x34 - 3 * x67;
    const double x126 = x46 * x73;
    const double x127 = x114 * x46;
    const double x128 = x127 * x9;
    const double x129 = t[8] * x128;
    const double x130 = 3 * t[2] * t[6] - 3 * x28;
    const double x131 = x46 * x78;
    const double x132 = t[7] * x128;
    const double x133 = 3 * x26 - 3 * x76;
    const double x134 = t[1] * x60;
    const double x135 = t[2] * x41;
    const double x136 = x46 * x83;
    const double x137 = 3 * t[2] * t[4] - 3 * x31;
    const double x138 = x46 * x88;
    const double x139 = t[5] * x128;
    const double x140 = 3 * x24 - 3 * x86;
    const double x141 = x46 * x94;
    const double x142 = t[4] * x128;
    const double x143 = 3 * t[1] * t[3] - 3 * x21;
    const double x144 = 2 * x3;
    const double x145 = 2 * x6;
    const double x146 = x144 + x145;
    const double x147 = (2.0 / 9.0) * x52;
    const double x148 = (4.0 / 9.0) * x37;
    const double x149 = x104 * x55;
    const double x150 = t[4] * x39;
    const double x151 = t[7] * x41;
    const double x152 = (2.0 / 9.0) * x109;
    const double x153 = t[2] * x20;
    const double x154 = x43 * x52;
    const double x155 = x110 * x43;
    const double x156 = t[1] * x114;
    const double x157 = x110 * x114;
    const double x158 = x147 * x20;
    const double x159 = t[0] * x90;
    const double x160 = t[1] * x127;
    const double x161 = t[6] * x128;
    const double x162 = t[0] * x59;
    const double x163 = t[3] * x128;
    const double x164 = (2.0 / 9.0) * x61;
    const double x165 = x104 * x64;
    const double x166 = (2.0 / 9.0) * x153;
    const double x167 = t[3] * x20;
    const double x168 = x43 * x61;
    const double x169 = x120 * x43;
    const double x170 = x114 * x124;
    const double x171 = x114 * x120;
    const double x172 = x164 * x20;
    const double x173 = t[2] * x127;
    const double x174 = 2 * x2;
    const double x175 = x174 + x97;
    const double x176 = 2 * x1;
    const double x177 = x100 + x176;
    const double x178 = (2.0 / 9.0) * x65;
    const double x179 = x104 * x69;
    const double x180 = t[0] * x89;
    const double x181 = (2.0 / 9.0) * x167;
    const double x182 = t[4] * x20;
    const double x183 = x43 * x65;
    const double x184 = x124 * x43;
    const double x185 = t[3] * x127;
    const double x186 = t[0] * x79;
    const double x187 = x178 * x20;
    const double x188 = t[4] * x60;
    const double x189 = t[8] * x39;
    const double x190 = t[2] * x128;
    const double x191 = t[1] * x128;
    const double x192 = 2 * x0;
    const double x193 = x145 + x192;
    const double x194 = (2.0 / 9.0) * x70;
    const double x195 = x104 * x73;
    const double x196 = t[1] * x79;
    const double x197 = (2.0 / 9.0) * x182;
    const double x198 = t[5] * x20;
    const double x199 = x43 * x70;
    const double x200 = x126 * x43;
    const double x201 = t[4] * x127;
    const double x202 = x127 * x73;
    const double x203 = x194 * x20;
    const double x204 = t[3] * x59;
    const double x205 = x113 * x46 * x9;
    const double x206 = (2.0 / 9.0) * x74;
    const double x207 = x104 * x78;
    const double x208 = (2.0 / 9.0) * x198;
    const double x209 = t[6] * x20;
    const double x210 = x131 * x43;
    const double x211 = x43 * x74;
    const double x212 = t[5] * x127;
    const double x213 = x127 * x78;
    const double x214 = x20 * x206;
    const double x215 = x174 + x96;
    const double x216 = x176 + x99;
    const double x217 = (2.0 / 9.0) * x80;
    const double x218 = x104 * x83;
    const double x219 = (2.0 / 9.0) * x209;
    const double x220 = t[7] * x20;
    const double x221 = x43 * x80;
    const double x222 = x136 * x43;
    const double x223 = t[6] * x127;
    const double x224 = x127 * x83;
    const double x225 = t[8] * x20;
    const double x226 = x144 + x192;
    const double x227 = (2.0 / 9.0) * x84;
    const double x228 = x104 * x88;
    const double x229 = (2.0 / 9.0) * x91;

    // --- value ---
    r.val = (1.0 / 9.0) * x20 * x37 * x9 - 1;

    // --- gradient (9 entries) ---
    r.grad[0] = t[0] * x45 + x42 * x44 + x50 * x51;
    r.grad[1] = t[1] * x45 + x44 * x52 + x55 * x56;
    r.grad[2] = t[2] * x45 + x44 * x61 + x56 * x64;
    r.grad[3] = t[3] * x45 + x44 * x65 + x56 * x69;
    r.grad[4] = t[4] * x45 + x44 * x70 + x56 * x73;
    r.grad[5] = t[5] * x45 + x44 * x74 + x56 * x78;
    r.grad[6] = t[6] * x45 + x44 * x80 + x56 * x83;
    r.grad[7] = t[7] * x45 + x44 * x84 + x56 * x88;
    r.grad[8] = t[8] * x45 + x44 * x91 + x56 * x94;

    // --- symmetric Hessian (45 unique entries) ---
    r.hess[0] = x102 * x50 * x9 + (4.0 / 9.0) * x103 * x50 + x105 * (3 * t[5] * t[7] - 3 * x10) +
                (4.0 / 9.0) * x42 * x95 + x44 * (x101 + x98) + x45;
    r.hess[1] = r.hess[9] = t[1] * x115 + x102 * x109 + x105 * x116 + x108 * x52 + x110 * x111 +
                            x110 * x113 + x112 * x52 + x44 * (-x106 - x107);
    r.hess[2] = r.hess[18] = t[2] * x115 + t[2] * x119 + x105 * x121 + x108 * x61 + x111 * x120 +
                             x112 * x61 + x113 * x120 + x44 * (-x117 - x118);
    r.hess[3] = r.hess[27] = t[3] * x115 + t[3] * x119 + x105 * x125 + x108 * x65 + x111 * x124 +
                             x112 * x65 + x113 * x124 + x44 * (-x122 - x123);
    r.hess[4] = r.hess[36] = t[4] * x115 + t[4] * x119 + x105 * x130 + x108 * x70 + x111 * x126 +
                             x112 * x70 + x113 * x126 - x129 + x44 * (4 * x21 + x93);
    r.hess[5] = r.hess[45] = t[5] * x115 + t[5] * x119 + x105 * x133 + x108 * x74 + x111 * x131 +
                             x112 * x74 + x113 * x131 + x132 + x44 * (4 * x24 + x87);
    r.hess[6] = r.hess[54] = t[6] * x115 + t[6] * x119 + x105 * x137 + x108 * x80 + x111 * x136 +
                             x112 * x80 + x113 * x136 + x44 * (-x134 - x135);
    r.hess[7] = r.hess[63] = t[7] * x115 + t[7] * x119 + x105 * x140 + x108 * x84 + x111 * x138 +
                             x112 * x84 + x113 * x138 + x139 + x44 * (4 * x26 + x77);
    r.hess[8] = r.hess[72] = t[8] * x115 + t[8] * x119 + x105 * x143 + x108 * x91 + x111 * x141 +
                             x112 * x91 + x113 * x141 - x142 + x44 * (4 * x28 + x72);
    r.hess[10] = t[1] * x110 * x148 + (4.0 / 9.0) * x109 * x52 + x110 * x147 * x9 + x116 * x149 +
                 x44 * (x146 + x98) + x45;
    r.hess[11] = r.hess[19] = t[2] * x157 + x120 * x154 + x120 * x156 + x121 * x149 + x147 * x153 +
                              x152 * x61 + x155 * x61 + x44 * (-x150 - x151);
    r.hess[12] = r.hess[28] = t[3] * x157 + t[3] * x158 + x124 * x154 + x124 * x156 + x125 * x149 +
                              x129 + x152 * x65 + x155 * x65 + x44 * (4 * t[1] * t[3] - x92);
    r.hess[13] = r.hess[37] = t[4] * x157 + t[4] * x158 + x126 * x154 + x130 * x149 + x152 * x70 +
                              x155 * x70 + x160 * x73 + x44 * (-x123 - x159);
    r.hess[14] = r.hess[46] = t[5] * x157 + t[5] * x158 + x131 * x154 + x133 * x149 + x152 * x74 +
                              x155 * x74 + x160 * x78 - x161 + x44 * (4 * x31 + x82);
    r.hess[15] = r.hess[55] = t[6] * x157 + t[6] * x158 + x136 * x154 + x137 * x149 - x139 +
                              x152 * x80 + x155 * x80 + x160 * x83 + x44 * (4 * t[1] * t[6] - x75);
    r.hess[16] = r.hess[64] = t[7] * x157 + t[7] * x158 + x138 * x154 + x140 * x149 + x152 * x84 +
                              x155 * x84 + x160 * x88 + x44 * (-x135 - x162);
    r.hess[17] = r.hess[73] = t[8] * x157 + t[8] * x158 + x141 * x154 + x143 * x149 + x152 * x91 +
                              x155 * x91 + x160 * x94 + x163 + x44 * (4 * x34 + x68);
    r.hess[20] = t[2] * x120 * x148 + x120 * x164 * x9 + x121 * x165 + (4.0 / 9.0) * x153 * x61 +
                 x44 * (x101 + x146) + x45;
    r.hess[21] = r.hess[29] = t[2] * x170 + t[3] * x171 + x124 * x168 + x125 * x165 - x132 +
                              x164 * x167 + x166 * x65 + x169 * x65 + x44 * (4 * t[2] * t[3] - x85);
    r.hess[22] = r.hess[38] = t[4] * x171 + t[4] * x172 + x126 * x168 + x130 * x165 + x161 +
                              x166 * x70 + x169 * x70 + x173 * x73 + x44 * (4 * t[2] * t[4] - x81);
    r.hess[23] = r.hess[47] = t[5] * x171 + t[5] * x172 + x131 * x168 + x133 * x165 + x166 * x74 +
                              x169 * x74 + x173 * x78 + x44 * (-x122 - x159);
    r.hess[24] = r.hess[56] = t[6] * x171 + t[6] * x172 + x136 * x168 + x137 * x165 + x142 +
                              x166 * x80 + x169 * x80 + x173 * x83 + x44 * (4 * t[2] * t[6] - x71);
    r.hess[25] = r.hess[65] = t[7] * x171 + t[7] * x172 + x138 * x168 + x140 * x165 - x163 +
                              x166 * x84 + x169 * x84 + x173 * x88 + x44 * (4 * t[2] * t[7] - x66);
    r.hess[26] = r.hess[74] = t[8] * x171 + t[8] * x172 + x141 * x168 + x143 * x165 + x166 * x91 +
                              x169 * x91 + x173 * x94 + x44 * (-x134 - x162);
    r.hess[30] = t[3] * x124 * x148 + x124 * x178 * x9 + x125 * x179 + (4.0 / 9.0) * x167 * x65 +
                 x44 * (x175 + x177) + x45;
    r.hess[31] = r.hess[39] = t[4] * x170 + x126 * x183 + x130 * x179 + x178 * x182 + x181 * x70 +
                              x184 * x70 + x185 * x73 + x44 * (-x107 - x180);
    r.hess[32] = r.hess[48] = t[5] * x170 + t[5] * x187 + x131 * x183 + x133 * x179 + x181 * x74 +
                              x184 * x74 + x185 * x78 + x44 * (-x118 - x186);
    r.hess[33] = r.hess[57] = t[6] * x170 + t[6] * x187 + x136 * x183 + x137 * x179 + x181 * x80 +
                              x184 * x80 + x185 * x83 + x44 * (-x188 - x189);
    r.hess[34] = r.hess[66] = t[7] * x170 + t[7] * x187 + x138 * x183 + x140 * x179 + x181 * x84 +
                              x184 * x84 + x185 * x88 - x190 + x44 * (4 * x13 + x63);
    r.hess[35] = r.hess[75] = t[8] * x170 + t[8] * x187 + x141 * x183 + x143 * x179 + x181 * x91 +
                              x184 * x91 + x185 * x94 + x191 + x44 * (4 * x16 + x54);
    r.hess[40] = t[4] * x126 * x148 + x126 * x194 * x9 + x130 * x195 + (4.0 / 9.0) * x182 * x70 +
                 x44 * (x175 + x193) + x45;
    r.hess[41] = r.hess[49] = t[5] * x202 + x131 * x199 + x133 * x195 + x194 * x198 + x197 * x74 +
                              x200 * x74 + x201 * x78 + x44 * (-x151 - x196);
    r.hess[42] = r.hess[58] = t[6] * x202 + t[6] * x203 + x136 * x199 + x137 * x195 + x190 +
                              x197 * x80 + x200 * x80 + x201 * x83 + x44 * (4 * t[4] * t[6] - x62);
    r.hess[43] = r.hess[67] = t[7] * x202 + t[7] * x203 + x138 * x199 + x140 * x195 + x197 * x84 +
                              x200 * x84 + x201 * x88 + x44 * (-x189 - x204);
    r.hess[44] = r.hess[76] = t[8] * x202 + t[8] * x203 + x141 * x199 + x143 * x195 + x197 * x91 +
                              x200 * x91 + x201 * x94 - x205 + x44 * (4 * x10 + x48);
    r.hess[50] = t[5] * x131 * x148 + x131 * x206 * x9 + x133 * x207 + (4.0 / 9.0) * x198 * x74 +
                 x44 * (x177 + x193) + x45;
    r.hess[51] = r.hess[59] = t[6] * x213 + x136 * x211 + x137 * x207 - x191 + x206 * x209 +
                              x208 * x80 + x210 * x80 + x212 * x83 + x44 * (4 * t[5] * t[6] - x53);
    r.hess[52] = r.hess[68] = t[7] * x213 + t[7] * x214 + x138 * x211 + x140 * x207 + x205 +
                              x208 * x84 + x210 * x84 + x212 * x88 + x44 * (4 * t[5] * t[7] - x47);
    r.hess[53] = r.hess[77] = t[8] * x213 + t[8] * x214 + x141 * x211 + x143 * x207 + x208 * x91 +
                              x210 * x91 + x212 * x94 + x44 * (-x188 - x204);
    r.hess[60] = t[6] * x136 * x148 + x136 * x217 * x9 + x137 * x218 + (4.0 / 9.0) * x209 * x80 +
                 x44 * (x215 + x216) + x45;
    r.hess[61] = r.hess[69] = t[7] * x224 + x138 * x221 + x140 * x218 + x217 * x220 + x219 * x84 +
                              x222 * x84 + x223 * x88 + x44 * (-x106 - x180);
    r.hess[62] = r.hess[78] = t[8] * x224 + x141 * x221 + x143 * x218 + x217 * x225 + x219 * x91 +
                              x222 * x91 + x223 * x94 + x44 * (-x117 - x186);
    r.hess[70] = t[7] * x138 * x148 + x138 * x227 * x9 + x140 * x228 + (4.0 / 9.0) * x220 * x84 +
                 x44 * (x215 + x226) + x45;
    r.hess[71] = r.hess[79] = t[7] * x127 * x94 + t[8] * x127 * x88 + x138 * x43 * x91 +
                              x141 * x43 * x84 + x143 * x228 + x220 * x229 + x225 * x227 +
                              x44 * (-x150 - x196);
    r.hess[80] = t[8] * x141 * x148 + x104 * x143 * x94 + x141 * x229 * x9 +
                 (4.0 / 9.0) * x225 * x91 + x44 * (x216 + x226) + x45;

    return r;
}

// --- fused value + grad + contracted Hessian (production path for D=3) ---
// Generated by bench/derive_cond3.py: same CSE body as mu_cond3_eval, but the
// 81-entry Hessian is contracted into jhj = Jbᵀ H Jb (3x3) on the fly (each
// entry produced, folded into the accumulator, discarded), so the full Hessian
// never lives in registers. Jb is the runtime 9x3 role-selected chain matrix.
// Parity vs mu_cond3_eval + explicit contraction: tests/cpp/test_metric_3d.cpp.
__attribute__((noinline)) inline void mu_cond3_jhj(
  const double* t, const double* Jb, double* val_out, double* grad_out, double* jhj_out)
{
    // --- Common Subexpressions (SymPy CSE) ---
    const double x0 = ((t[0] * t[0]));
    const double x1 = ((t[1] * t[1]));
    const double x2 = ((t[2] * t[2]));
    const double x3 = ((t[3] * t[3]));
    const double x4 = ((t[4] * t[4]));
    const double x5 = ((t[5] * t[5]));
    const double x6 = ((t[6] * t[6]));
    const double x7 = ((t[7] * t[7]));
    const double x8 = ((t[8] * t[8]));
    const double x9 = x0 + x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8;
    const double x10 = t[4] * t[8];
    const double x11 = t[5] * t[7];
    const double x12 = x10 - x11;
    const double x13 = t[3] * t[7];
    const double x14 = t[4] * t[6];
    const double x15 = x13 - x14;
    const double x16 = t[3] * t[8];
    const double x17 = t[5] * t[6];
    const double x18 = x16 - x17;
    const double x19 = t[0] * x12 - t[1] * x18 + t[2] * x15;
    const double x20 = (1.0 / (x19 * x19));
    const double x21 = t[0] * t[4];
    const double x22 = t[1] * t[3];
    const double x23 = x21 - x22;
    const double x24 = t[0] * t[5];
    const double x25 = t[2] * t[3] - x24;
    const double x26 = t[0] * t[7];
    const double x27 = t[1] * t[6] - x26;
    const double x28 = t[0] * t[8];
    const double x29 = t[2] * t[6];
    const double x30 = x28 - x29;
    const double x31 = t[1] * t[5];
    const double x32 = t[2] * t[4];
    const double x33 = x31 - x32;
    const double x34 = t[1] * t[8];
    const double x35 = t[2] * t[7] - x34;
    const double x36 = -x18;
    const double x37 = ((x12 * x12)) + ((x15 * x15)) + ((x23 * x23)) + ((x25 * x25)) +
                       ((x27 * x27)) + ((x30 * x30)) + ((x33 * x33)) + ((x35 * x35)) +
                       ((x36 * x36));
    const double x38 = 2 * x23;
    const double x39 = 2 * t[5];
    const double x40 = 2 * x27;
    const double x41 = 2 * t[8];
    const double x42 = t[4] * x38 - t[7] * x40 - x25 * x39 + x30 * x41;
    const double x43 = (1.0 / 9.0) * x9;
    const double x44 = x20 * x43;
    const double x45 = (2.0 / 9.0) * x20 * x37;
    const double inv_x19 = x20 * x19;  // 1/D
    const double x46 = x20 * inv_x19;
    const double x47 = 2 * x10;
    const double x48 = -2 * x11;
    const double x49 = -x47 - x48;
    const double x50 = x46 * x49;
    const double x51 = x37 * x43;
    const double x52 = -t[3] * x38 + 2 * t[5] * x33 + 2 * t[6] * x27 - x35 * x41;
    const double x53 = 2 * x16;
    const double x54 = -2 * x17;
    const double x55 = x53 + x54;
    const double x56 = x46 * x51;
    const double x57 = 2 * x25;
    const double x58 = 2 * x33;
    const double x59 = 2 * t[6];
    const double x60 = 2 * t[7];
    const double x61 = t[3] * x57 - t[4] * x58 - x30 * x59 + x35 * x60;
    const double x62 = 2 * x13;
    const double x63 = -2 * x14;
    const double x64 = -x62 - x63;
    const double x65 = -t[1] * x38 + 2 * t[2] * x25 + 2 * t[7] * x15 - x36 * x41;
    const double x66 = 2 * x34;
    const double x67 = t[2] * t[7];
    const double x68 = -2 * x67;
    const double x69 = x66 + x68;
    const double x70 = t[0] * x38 - t[2] * x58 + x12 * x41 - x15 * x59;
    const double x71 = 2 * x28;
    const double x72 = -2 * x29;
    const double x73 = -x71 - x72;
    const double x74 = -t[0] * x57 + 2 * t[1] * x33 + 2 * t[6] * x36 - x12 * x60;
    const double x75 = 2 * x26;
    const double x76 = t[1] * t[6];
    const double x77 = -2 * x76;
    const double x78 = x75 + x77;
    const double x79 = 2 * t[2];
    const double x80 = t[1] * x40 - 2 * t[4] * x15 - x30 * x79 + x36 * x39;
    const double x81 = 2 * x31;
    const double x82 = -2 * x32;
    const double x83 = -x81 - x82;
    const double x84 = -t[0] * x40 + 2 * t[2] * x35 + 2 * t[3] * x15 - x12 * x39;
    const double x85 = 2 * x24;
    const double x86 = t[2] * t[3];
    const double x87 = -2 * x86;
    const double x88 = x85 + x87;
    const double x89 = 2 * t[1];
    const double x90 = 2 * t[3];
    const double x91 = 2 * t[0] * x30 + 2 * t[4] * x12 - x35 * x89 - x36 * x90;
    const double x92 = 2 * x21;
    const double x93 = -2 * x22;
    const double x94 = -x92 - x93;
    const double x95 = t[0] * x20;
    const double x96 = 2 * x5;
    const double x97 = 2 * x8;
    const double x98 = x96 + x97;
    const double x99 = 2 * x4;
    const double x100 = 2 * x7;
    const double x101 = x100 + x99;
    const double x102 = (2.0 / 9.0) * x42;
    const double x103 = t[0] * x37;
    const double x104 = x51 * x20 * x20;
    const double x105 = x104 * x49;
    const double x106 = t[4] * x90;
    const double x107 = t[7] * x59;
    const double x108 = (2.0 / 9.0) * x95;
    const double x109 = t[1] * x20;
    const double x110 = x46 * x55;
    const double x111 = x42 * x43;
    const double x112 = x43 * x50;
    const double x113 = (2.0 / 9.0) * x103;
    const double x114 = (2.0 / 9.0) * x37;
    const double x115 = x114 * x50;
    const double x116 = 3 * x16 - 3 * x17;
    const double x117 = t[3] * x39;
    const double x118 = t[6] * x41;
    const double x119 = x102 * x20;
    const double x120 = x46 * x64;
    const double x121 = 3 * t[4] * t[6] - 3 * x13;
    const double x122 = t[4] * x89;
    const double x123 = t[2] * x39;
    const double x124 = x46 * x69;
    const double x125 = 3 * x34 - 3 * x67;
    const double x126 = x46 * x73;
    const double x127 = x114 * x46;
    const double x128 = x127 * x9;
    const double x129 = t[8] * x128;
    const double x130 = 3 * t[2] * t[6] - 3 * x28;
    const double x131 = x46 * x78;
    const double x132 = t[7] * x128;
    const double x133 = 3 * x26 - 3 * x76;
    const double x134 = t[1] * x60;
    const double x135 = t[2] * x41;
    const double x136 = x46 * x83;
    const double x137 = 3 * t[2] * t[4] - 3 * x31;
    const double x138 = x46 * x88;
    const double x139 = t[5] * x128;
    const double x140 = 3 * x24 - 3 * x86;
    const double x141 = x46 * x94;
    const double x142 = t[4] * x128;
    const double x143 = 3 * t[1] * t[3] - 3 * x21;
    const double x144 = 2 * x3;
    const double x145 = 2 * x6;
    const double x146 = x144 + x145;
    const double x147 = (2.0 / 9.0) * x52;
    const double x148 = (4.0 / 9.0) * x37;
    const double x149 = x104 * x55;
    const double x150 = t[4] * x39;
    const double x151 = t[7] * x41;
    const double x152 = (2.0 / 9.0) * x109;
    const double x153 = t[2] * x20;
    const double x154 = x43 * x52;
    const double x155 = x110 * x43;
    const double x156 = t[1] * x114;
    const double x157 = x110 * x114;
    const double x158 = x147 * x20;
    const double x159 = t[0] * x90;
    const double x160 = t[1] * x127;
    const double x161 = t[6] * x128;
    const double x162 = t[0] * x59;
    const double x163 = t[3] * x128;
    const double x164 = (2.0 / 9.0) * x61;
    const double x165 = x104 * x64;
    const double x166 = (2.0 / 9.0) * x153;
    const double x167 = t[3] * x20;
    const double x168 = x43 * x61;
    const double x169 = x120 * x43;
    const double x170 = x114 * x124;
    const double x171 = x114 * x120;
    const double x172 = x164 * x20;
    const double x173 = t[2] * x127;
    const double x174 = 2 * x2;
    const double x175 = x174 + x97;
    const double x176 = 2 * x1;
    const double x177 = x100 + x176;
    const double x178 = (2.0 / 9.0) * x65;
    const double x179 = x104 * x69;
    const double x180 = t[0] * x89;
    const double x181 = (2.0 / 9.0) * x167;
    const double x182 = t[4] * x20;
    const double x183 = x43 * x65;
    const double x184 = x124 * x43;
    const double x185 = t[3] * x127;
    const double x186 = t[0] * x79;
    const double x187 = x178 * x20;
    const double x188 = t[4] * x60;
    const double x189 = t[8] * x39;
    const double x190 = t[2] * x128;
    const double x191 = t[1] * x128;
    const double x192 = 2 * x0;
    const double x193 = x145 + x192;
    const double x194 = (2.0 / 9.0) * x70;
    const double x195 = x104 * x73;
    const double x196 = t[1] * x79;
    const double x197 = (2.0 / 9.0) * x182;
    const double x198 = t[5] * x20;
    const double x199 = x43 * x70;
    const double x200 = x126 * x43;
    const double x201 = t[4] * x127;
    const double x202 = x127 * x73;
    const double x203 = x194 * x20;
    const double x204 = t[3] * x59;
    const double x205 = x113 * x46 * x9;
    const double x206 = (2.0 / 9.0) * x74;
    const double x207 = x104 * x78;
    const double x208 = (2.0 / 9.0) * x198;
    const double x209 = t[6] * x20;
    const double x210 = x131 * x43;
    const double x211 = x43 * x74;
    const double x212 = t[5] * x127;
    const double x213 = x127 * x78;
    const double x214 = x20 * x206;
    const double x215 = x174 + x96;
    const double x216 = x176 + x99;
    const double x217 = (2.0 / 9.0) * x80;
    const double x218 = x104 * x83;
    const double x219 = (2.0 / 9.0) * x209;
    const double x220 = t[7] * x20;
    const double x221 = x43 * x80;
    const double x222 = x136 * x43;
    const double x223 = t[6] * x127;
    const double x224 = x127 * x83;
    const double x225 = t[8] * x20;
    const double x226 = x144 + x192;
    const double x227 = (2.0 / 9.0) * x84;
    const double x228 = x104 * x88;
    const double x229 = (2.0 / 9.0) * x91;

    // --- value ---
    *val_out = (1.0 / 9.0) * x20 * x37 * x9 - 1;

    // --- gradient (9 entries) ---
    grad_out[0] = t[0] * x45 + x42 * x44 + x50 * x51;
    grad_out[1] = t[1] * x45 + x44 * x52 + x55 * x56;
    grad_out[2] = t[2] * x45 + x44 * x61 + x56 * x64;
    grad_out[3] = t[3] * x45 + x44 * x65 + x56 * x69;
    grad_out[4] = t[4] * x45 + x44 * x70 + x56 * x73;
    grad_out[5] = t[5] * x45 + x44 * x74 + x56 * x78;
    grad_out[6] = t[6] * x45 + x44 * x80 + x56 * x83;
    grad_out[7] = t[7] * x45 + x44 * x84 + x56 * x88;
    grad_out[8] = t[8] * x45 + x44 * x91 + x56 * x94;

    // --- contracted Hessian jhj = Jb^T H Jb (3x3 row-major) ---
    for (int _k = 0; _k < 9; ++_k) { jhj_out[_k] = 0.0; }
    {
        const double h = x102 * x50 * x9 + (4.0 / 9.0) * x103 * x50 +
                         x105 * (3 * t[5] * t[7] - 3 * x10) + (4.0 / 9.0) * x42 * x95 +
                         x44 * (x101 + x98) + x45;
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * Jb[(0 * 3) + p] * Jb[(0 * 3) + qcol];
            }
        }
    }
    {
        const double h = t[1] * x115 + x102 * x109 + x105 * x116 + x108 * x52 + x110 * x111 +
                         x110 * x113 + x112 * x52 + x44 * (-x106 - x107);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(0 * 3) + p] * Jb[(1 * 3) + qcol]) +
                                                (Jb[(1 * 3) + p] * Jb[(0 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[2] * x115 + t[2] * x119 + x105 * x121 + x108 * x61 + x111 * x120 +
                         x112 * x61 + x113 * x120 + x44 * (-x117 - x118);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(0 * 3) + p] * Jb[(2 * 3) + qcol]) +
                                                (Jb[(2 * 3) + p] * Jb[(0 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[3] * x115 + t[3] * x119 + x105 * x125 + x108 * x65 + x111 * x124 +
                         x112 * x65 + x113 * x124 + x44 * (-x122 - x123);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(0 * 3) + p] * Jb[(3 * 3) + qcol]) +
                                                (Jb[(3 * 3) + p] * Jb[(0 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[4] * x115 + t[4] * x119 + x105 * x130 + x108 * x70 + x111 * x126 +
                         x112 * x70 + x113 * x126 - x129 + x44 * (4 * x21 + x93);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(0 * 3) + p] * Jb[(4 * 3) + qcol]) +
                                                (Jb[(4 * 3) + p] * Jb[(0 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[5] * x115 + t[5] * x119 + x105 * x133 + x108 * x74 + x111 * x131 +
                         x112 * x74 + x113 * x131 + x132 + x44 * (4 * x24 + x87);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(0 * 3) + p] * Jb[(5 * 3) + qcol]) +
                                                (Jb[(5 * 3) + p] * Jb[(0 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[6] * x115 + t[6] * x119 + x105 * x137 + x108 * x80 + x111 * x136 +
                         x112 * x80 + x113 * x136 + x44 * (-x134 - x135);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(0 * 3) + p] * Jb[(6 * 3) + qcol]) +
                                                (Jb[(6 * 3) + p] * Jb[(0 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[7] * x115 + t[7] * x119 + x105 * x140 + x108 * x84 + x111 * x138 +
                         x112 * x84 + x113 * x138 + x139 + x44 * (4 * x26 + x77);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(0 * 3) + p] * Jb[(7 * 3) + qcol]) +
                                                (Jb[(7 * 3) + p] * Jb[(0 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[8] * x115 + t[8] * x119 + x105 * x143 + x108 * x91 + x111 * x141 +
                         x112 * x91 + x113 * x141 - x142 + x44 * (4 * x28 + x72);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(0 * 3) + p] * Jb[(8 * 3) + qcol]) +
                                                (Jb[(8 * 3) + p] * Jb[(0 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[1] * x110 * x148 + (4.0 / 9.0) * x109 * x52 + x110 * x147 * x9 +
                         x116 * x149 + x44 * (x146 + x98) + x45;
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * Jb[(1 * 3) + p] * Jb[(1 * 3) + qcol];
            }
        }
    }
    {
        const double h = t[2] * x157 + x120 * x154 + x120 * x156 + x121 * x149 + x147 * x153 +
                         x152 * x61 + x155 * x61 + x44 * (-x150 - x151);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(1 * 3) + p] * Jb[(2 * 3) + qcol]) +
                                                (Jb[(2 * 3) + p] * Jb[(1 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[3] * x157 + t[3] * x158 + x124 * x154 + x124 * x156 + x125 * x149 +
                         x129 + x152 * x65 + x155 * x65 + x44 * (4 * t[1] * t[3] - x92);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(1 * 3) + p] * Jb[(3 * 3) + qcol]) +
                                                (Jb[(3 * 3) + p] * Jb[(1 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[4] * x157 + t[4] * x158 + x126 * x154 + x130 * x149 + x152 * x70 +
                         x155 * x70 + x160 * x73 + x44 * (-x123 - x159);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(1 * 3) + p] * Jb[(4 * 3) + qcol]) +
                                                (Jb[(4 * 3) + p] * Jb[(1 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[5] * x157 + t[5] * x158 + x131 * x154 + x133 * x149 + x152 * x74 +
                         x155 * x74 + x160 * x78 - x161 + x44 * (4 * x31 + x82);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(1 * 3) + p] * Jb[(5 * 3) + qcol]) +
                                                (Jb[(5 * 3) + p] * Jb[(1 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[6] * x157 + t[6] * x158 + x136 * x154 + x137 * x149 - x139 + x152 * x80 +
                         x155 * x80 + x160 * x83 + x44 * (4 * t[1] * t[6] - x75);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(1 * 3) + p] * Jb[(6 * 3) + qcol]) +
                                                (Jb[(6 * 3) + p] * Jb[(1 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[7] * x157 + t[7] * x158 + x138 * x154 + x140 * x149 + x152 * x84 +
                         x155 * x84 + x160 * x88 + x44 * (-x135 - x162);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(1 * 3) + p] * Jb[(7 * 3) + qcol]) +
                                                (Jb[(7 * 3) + p] * Jb[(1 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[8] * x157 + t[8] * x158 + x141 * x154 + x143 * x149 + x152 * x91 +
                         x155 * x91 + x160 * x94 + x163 + x44 * (4 * x34 + x68);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(1 * 3) + p] * Jb[(8 * 3) + qcol]) +
                                                (Jb[(8 * 3) + p] * Jb[(1 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[2] * x120 * x148 + x120 * x164 * x9 + x121 * x165 +
                         (4.0 / 9.0) * x153 * x61 + x44 * (x101 + x146) + x45;
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * Jb[(2 * 3) + p] * Jb[(2 * 3) + qcol];
            }
        }
    }
    {
        const double h = t[2] * x170 + t[3] * x171 + x124 * x168 + x125 * x165 - x132 +
                         x164 * x167 + x166 * x65 + x169 * x65 + x44 * (4 * t[2] * t[3] - x85);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(2 * 3) + p] * Jb[(3 * 3) + qcol]) +
                                                (Jb[(3 * 3) + p] * Jb[(2 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[4] * x171 + t[4] * x172 + x126 * x168 + x130 * x165 + x161 + x166 * x70 +
                         x169 * x70 + x173 * x73 + x44 * (4 * t[2] * t[4] - x81);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(2 * 3) + p] * Jb[(4 * 3) + qcol]) +
                                                (Jb[(4 * 3) + p] * Jb[(2 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[5] * x171 + t[5] * x172 + x131 * x168 + x133 * x165 + x166 * x74 +
                         x169 * x74 + x173 * x78 + x44 * (-x122 - x159);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(2 * 3) + p] * Jb[(5 * 3) + qcol]) +
                                                (Jb[(5 * 3) + p] * Jb[(2 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[6] * x171 + t[6] * x172 + x136 * x168 + x137 * x165 + x142 + x166 * x80 +
                         x169 * x80 + x173 * x83 + x44 * (4 * t[2] * t[6] - x71);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(2 * 3) + p] * Jb[(6 * 3) + qcol]) +
                                                (Jb[(6 * 3) + p] * Jb[(2 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[7] * x171 + t[7] * x172 + x138 * x168 + x140 * x165 - x163 + x166 * x84 +
                         x169 * x84 + x173 * x88 + x44 * (4 * t[2] * t[7] - x66);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(2 * 3) + p] * Jb[(7 * 3) + qcol]) +
                                                (Jb[(7 * 3) + p] * Jb[(2 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[8] * x171 + t[8] * x172 + x141 * x168 + x143 * x165 + x166 * x91 +
                         x169 * x91 + x173 * x94 + x44 * (-x134 - x162);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(2 * 3) + p] * Jb[(8 * 3) + qcol]) +
                                                (Jb[(8 * 3) + p] * Jb[(2 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[3] * x124 * x148 + x124 * x178 * x9 + x125 * x179 +
                         (4.0 / 9.0) * x167 * x65 + x44 * (x175 + x177) + x45;
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * Jb[(3 * 3) + p] * Jb[(3 * 3) + qcol];
            }
        }
    }
    {
        const double h = t[4] * x170 + x126 * x183 + x130 * x179 + x178 * x182 + x181 * x70 +
                         x184 * x70 + x185 * x73 + x44 * (-x107 - x180);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(3 * 3) + p] * Jb[(4 * 3) + qcol]) +
                                                (Jb[(4 * 3) + p] * Jb[(3 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[5] * x170 + t[5] * x187 + x131 * x183 + x133 * x179 + x181 * x74 +
                         x184 * x74 + x185 * x78 + x44 * (-x118 - x186);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(3 * 3) + p] * Jb[(5 * 3) + qcol]) +
                                                (Jb[(5 * 3) + p] * Jb[(3 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[6] * x170 + t[6] * x187 + x136 * x183 + x137 * x179 + x181 * x80 +
                         x184 * x80 + x185 * x83 + x44 * (-x188 - x189);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(3 * 3) + p] * Jb[(6 * 3) + qcol]) +
                                                (Jb[(6 * 3) + p] * Jb[(3 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[7] * x170 + t[7] * x187 + x138 * x183 + x140 * x179 + x181 * x84 +
                         x184 * x84 + x185 * x88 - x190 + x44 * (4 * x13 + x63);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(3 * 3) + p] * Jb[(7 * 3) + qcol]) +
                                                (Jb[(7 * 3) + p] * Jb[(3 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[8] * x170 + t[8] * x187 + x141 * x183 + x143 * x179 + x181 * x91 +
                         x184 * x91 + x185 * x94 + x191 + x44 * (4 * x16 + x54);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(3 * 3) + p] * Jb[(8 * 3) + qcol]) +
                                                (Jb[(8 * 3) + p] * Jb[(3 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[4] * x126 * x148 + x126 * x194 * x9 + x130 * x195 +
                         (4.0 / 9.0) * x182 * x70 + x44 * (x175 + x193) + x45;
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * Jb[(4 * 3) + p] * Jb[(4 * 3) + qcol];
            }
        }
    }
    {
        const double h = t[5] * x202 + x131 * x199 + x133 * x195 + x194 * x198 + x197 * x74 +
                         x200 * x74 + x201 * x78 + x44 * (-x151 - x196);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(4 * 3) + p] * Jb[(5 * 3) + qcol]) +
                                                (Jb[(5 * 3) + p] * Jb[(4 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[6] * x202 + t[6] * x203 + x136 * x199 + x137 * x195 + x190 + x197 * x80 +
                         x200 * x80 + x201 * x83 + x44 * (4 * t[4] * t[6] - x62);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(4 * 3) + p] * Jb[(6 * 3) + qcol]) +
                                                (Jb[(6 * 3) + p] * Jb[(4 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[7] * x202 + t[7] * x203 + x138 * x199 + x140 * x195 + x197 * x84 +
                         x200 * x84 + x201 * x88 + x44 * (-x189 - x204);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(4 * 3) + p] * Jb[(7 * 3) + qcol]) +
                                                (Jb[(7 * 3) + p] * Jb[(4 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[8] * x202 + t[8] * x203 + x141 * x199 + x143 * x195 + x197 * x91 +
                         x200 * x91 + x201 * x94 - x205 + x44 * (4 * x10 + x48);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(4 * 3) + p] * Jb[(8 * 3) + qcol]) +
                                                (Jb[(8 * 3) + p] * Jb[(4 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[5] * x131 * x148 + x131 * x206 * x9 + x133 * x207 +
                         (4.0 / 9.0) * x198 * x74 + x44 * (x177 + x193) + x45;
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * Jb[(5 * 3) + p] * Jb[(5 * 3) + qcol];
            }
        }
    }
    {
        const double h = t[6] * x213 + x136 * x211 + x137 * x207 - x191 + x206 * x209 + x208 * x80 +
                         x210 * x80 + x212 * x83 + x44 * (4 * t[5] * t[6] - x53);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(5 * 3) + p] * Jb[(6 * 3) + qcol]) +
                                                (Jb[(6 * 3) + p] * Jb[(5 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[7] * x213 + t[7] * x214 + x138 * x211 + x140 * x207 + x205 + x208 * x84 +
                         x210 * x84 + x212 * x88 + x44 * (4 * t[5] * t[7] - x47);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(5 * 3) + p] * Jb[(7 * 3) + qcol]) +
                                                (Jb[(7 * 3) + p] * Jb[(5 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[8] * x213 + t[8] * x214 + x141 * x211 + x143 * x207 + x208 * x91 +
                         x210 * x91 + x212 * x94 + x44 * (-x188 - x204);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(5 * 3) + p] * Jb[(8 * 3) + qcol]) +
                                                (Jb[(8 * 3) + p] * Jb[(5 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[6] * x136 * x148 + x136 * x217 * x9 + x137 * x218 +
                         (4.0 / 9.0) * x209 * x80 + x44 * (x215 + x216) + x45;
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * Jb[(6 * 3) + p] * Jb[(6 * 3) + qcol];
            }
        }
    }
    {
        const double h = t[7] * x224 + x138 * x221 + x140 * x218 + x217 * x220 + x219 * x84 +
                         x222 * x84 + x223 * x88 + x44 * (-x106 - x180);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(6 * 3) + p] * Jb[(7 * 3) + qcol]) +
                                                (Jb[(7 * 3) + p] * Jb[(6 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[8] * x224 + x141 * x221 + x143 * x218 + x217 * x225 + x219 * x91 +
                         x222 * x91 + x223 * x94 + x44 * (-x117 - x186);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(6 * 3) + p] * Jb[(8 * 3) + qcol]) +
                                                (Jb[(8 * 3) + p] * Jb[(6 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[7] * x138 * x148 + x138 * x227 * x9 + x140 * x228 +
                         (4.0 / 9.0) * x220 * x84 + x44 * (x215 + x226) + x45;
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * Jb[(7 * 3) + p] * Jb[(7 * 3) + qcol];
            }
        }
    }
    {
        const double h = t[7] * x127 * x94 + t[8] * x127 * x88 + x138 * x43 * x91 +
                         x141 * x43 * x84 + x143 * x228 + x220 * x229 + x225 * x227 +
                         x44 * (-x150 - x196);
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * ((Jb[(7 * 3) + p] * Jb[(8 * 3) + qcol]) +
                                                (Jb[(8 * 3) + p] * Jb[(7 * 3) + qcol]));
            }
        }
    }
    {
        const double h = t[8] * x141 * x148 + x104 * x143 * x94 + x141 * x229 * x9 +
                         (4.0 / 9.0) * x225 * x91 + x44 * (x216 + x226) + x45;
        for (int p = 0; p < 3; ++p) {
            for (int qcol = 0; qcol < 3; ++qcol) {
                jhj_out[(p * 3) + qcol] += h * Jb[(8 * 3) + p] * Jb[(8 * 3) + qcol];
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Objective concept + closed set of objective kinds (barrier / δ-untangle).
//
// An Objective supplies the per-cell μ value/grad/Hess w.r.t. vec(T) (μ is the
// objective integrand; the energy E = Σ μ is accumulated by the kernels) plus
// the line-search accept policy on min det A. The kinds are a closed set, so
// they live in a
// std::variant and are dispatched **once per run** with std::visit (outside the
// hot loop) to instantiate a monomorphic, fully-concrete kernel — no virtuals,
// no per-DOF type dispatch on device.
// ---------------------------------------------------------------------------
template <class M, int D>
concept ObjectiveD = requires(const M& m, const VecTN<D>& t, double det) {
    { m.value(t) } -> std::convertible_to<double>;
    { m.grad(t) } -> std::convertible_to<GradN<D>>;
    { m.hess(t) } -> std::convertible_to<HessN<D>>;
    // Line-search accept test on min det A for this objective's regime.
    { m.accept_mindet(det) } -> std::convertible_to<bool>;
};

// Barrier shape objective (minimises the shape-distortion metric μ). D=2 keeps
// the classic shape_2d closed forms (bit-identical production path); D=3 uses
// the condition-number barrier μ_cond3 with dual-AD derivatives.
template <int D> struct ShapeObjectiveT {
    static_assert(D == 2 || D == 3, "ShapeObjectiveT: unsupported dimension");
    static constexpr int kN = dim::vecT(D);

    [[nodiscard]] double value(const VecTN<D>& t) const
    {
        if constexpr (D == 2) {
            return mu_value(t);
        } else {
            return mu_cond3(t);
        }
    }
    [[nodiscard]] GradN<D> grad(const VecTN<D>& t) const
    {
        if constexpr (D == 2) {
            return mu_grad_closedform(t);
        } else {
            MuCond3Eval r = mu_cond3_eval(t.data());
            GradN<D> g;
            for (int i = 0; i < kN; ++i) { g[i] = r.grad[i]; }
            return g;
        }
    }
    [[nodiscard]] HessN<D> hess(const VecTN<D>& t) const
    {
        if constexpr (D == 2) {
            return mu_hess_closedform(t);
        } else {
            MuCond3Eval r = mu_cond3_eval(t.data());
            HessN<D> H {};
            for (int i = 0; i < 81; ++i) { H[i] = r.hess[i]; }
            return H;
        }
    }
    // Fused value + metric gradient + contracted Hessian jhj = Jbᵀ H Jb (D=3
    // only): the patch hot path's single metric entry point. Avoids ever
    // materialising the 81-entry Hessian (the register footprint pinning the 3D
    // sweep kernel), and computes value/grad/contraction in one CSE pass instead
    // of the separate value + grad + hess calls. @p Jb is the runtime 9×3 chain
    // matrix (role-selected J columns); @p val/@p grad/@p jhj are out-params.
    void eval_jhj(const VecTN<D>& t, const double* Jb, double* val, double* grad, double* jhj) const
        requires(D == 3)
    { mu_cond3_jhj(t.data(), Jb, val, grad, jhj); }
    // Barrier: a step is only valid if every cell stays positively oriented.
    [[nodiscard]] bool accept_mindet(double mindet) const { return mindet > 0.0; }
};

// δ-continuation untangle objective: surrogate value + dual-AD grad/Hess, with the
// relaxed accept rule (the surrogate is finite on folded cells, so min det A may
// be ≤ 0 during continuation). D=2 keeps the existing surrogate exactly; D=3
// substitutes Dh into the condition-number barrier.
template <int D> struct UntangleObjectiveT {
    static_assert(D == 2 || D == 3, "UntangleObjectiveT: unsupported dimension");
    static constexpr int kN = dim::vecT(D);
    double delta {0.0};

    [[nodiscard]] double value(const VecTN<D>& t) const
    {
        if constexpr (D == 2) {
            return mu_untangle(t[0], t[1], t[2], t[3], delta);
        } else {
            return mu_cond3_untangle(t, delta);
        }
    }
    [[nodiscard]] GradN<D> grad(const VecTN<D>& t) const
    {
        if constexpr (D == 2) {
            using Dv = Dual<kVecT>;
            const Dv r = mu_untangle(seed_dual<kVecT>(t[0], 0),
                                     seed_dual<kVecT>(t[1], 1),
                                     seed_dual<kVecT>(t[2], 2),
                                     seed_dual<kVecT>(t[3], 3),
                                     delta);
            return GradN<D> {r.g[0], r.g[1], r.g[2], r.g[3]};
        } else {
            std::array<Dual<kN>, kN> td;
            for (int i = 0; i < kN; ++i) { td[i] = seed_dual<kN>(t[i], i); }
            const Dual<kN> r = mu_cond3_untangle(td, delta);
            GradN<D> g;
            for (int i = 0; i < kN; ++i) { g[i] = r.g[i]; }
            return g;
        }
    }
    [[nodiscard]] HessN<D> hess(const VecTN<D>& t) const
    {
        if constexpr (D == 2) {
            using Dv = Dual2<kVecT>;
            const Dv r = mu_untangle(seed_dual2<kVecT>(t[0], 0),
                                     seed_dual2<kVecT>(t[1], 1),
                                     seed_dual2<kVecT>(t[2], 2),
                                     seed_dual2<kVecT>(t[3], 3),
                                     delta);
            HessN<D> H {};
            for (int i = 0; i < kVecT; ++i) {
                for (int j = 0; j < kVecT; ++j) { H[(i * kVecT) + j] = r.h[i][j]; }
            }
            return H;
        } else {
            std::array<Dual2<kN>, kN> td;
            for (int i = 0; i < kN; ++i) { td[i] = seed_dual2<kN>(t[i], i); }
            const Dual2<kN> r = mu_cond3_untangle(td, delta);
            HessN<D> H {};
            for (int i = 0; i < kN; ++i) {
                for (int j = 0; j < kN; ++j) { H[(i * kN) + j] = r.h[i][j]; }
            }
            return H;
        }
    }
    [[nodiscard]] bool accept_mindet(double) const { return true; }
};

// Closed set of objective kinds for std::visit dispatch.
template <int D> using ObjectiveKindT = std::variant<ShapeObjectiveT<D>, UntangleObjectiveT<D>>;

// Select the objective for a run. `phase == "untangle"` picks the δ-surrogate;
// anything else (default "barrier") picks the shape barrier.
template <int D = kDefaultDim>
inline ObjectiveKindT<D> make_objective(std::string_view phase, double delta)
{
    if (phase == "untangle") { return UntangleObjectiveT<D> {delta}; }
    return ShapeObjectiveT<D> {};
}

// D=2 legacy aliases for the oracle surface and existing call sites.
using ShapeObjective = ShapeObjectiveT<2>;
using UntangleObjective = UntangleObjectiveT<2>;
using ObjectiveKind = ObjectiveKindT<2>;

template <class M>
concept Objective = ObjectiveD<M, 2>;

static_assert(Objective<ShapeObjective>);
static_assert(Objective<UntangleObjective>);

}  // namespace egg
