// Required Notice: Copyright (c) Shahzeb Imran and Egg contributors
//
// PolyForm Noncommercial License 2.0.0-pre.2
// https://github.com/bezmi/egg/blob/main/LICENSE.md
// Free to use and redistribute for personal and noncommercial purposes.
// See the license for details.
// For commercial licensing, contact s.imran@tuta.io

/// @file metric.hpp
/// TMOP metrics. 2D shape_2d mu(T) = |T|²/(2 det T) − 1 with closed-form
/// value/grad/Hess (production) and dual-AD (parity); mirrors the NumPy oracle
/// egg.smoothing.metrics exactly; vec(T) = [a, b, c, d] = [T00, T01, T10, T11].
/// 3D mu_cond3 likewise has a closed-form path (mu_cond3_eval) generated by
/// scripts/derive_cond3.py — regenerate via the script if the math changes and
/// verify parity against the Dual2<9> AD path (tests/cpp/test_metric_3d.cpp).
#pragma once

#include "core.hpp"
#include "dual.hpp"

#include <array>
#include <cmath>
#include <concepts>
#include <string_view>
#include <variant>

namespace egg
{

// D=2 aliases of the VecTN/GradN/HessN<D> shapes (used by the closed-form 2D
// metric and the oracle surface).
using VecT = VecTN<2>;  ///< [a, b, c, d]
using Grad = GradN<2>;  ///< dmu/dvec(T)
using Hess = HessN<2>;  ///< (d²)×(d²) row-major

/// Generic scalar shape_2d metric, reused for real / Dual<4> / Dual2<4>:
/// mu = s/(2D) − 1 with D = ad − bc, s = a² + b² + c² + d².
template <typename T> constexpr T mu_shape2d(const T& a, const T& b, const T& c, const T& d)
{
    const T D = a * d - b * c;
    const T s = a * a + b * b + c * c + d * d;
    return s / (2.0_r * D) - 1.0_r;
}

inline real mu_value(const VecT& t) { return mu_shape2d(t[0], t[1], t[2], t[3]); }

/// Closed-form gradient (matches _shape2d_value_grad).
inline Grad mu_grad_closedform(const VecT& t)
{
    const real a = t[0], b = t[1], c = t[2], d = t[3];
    const real D = (a * d) - (b * c);
    const real s = (a * a) + (b * b) + (c * c) + (d * d);
    const real coef = s / (2.0_r * D * D);
    return Grad {(a / D) - (coef * d),
                 (b / D) + (coef * c),
                 (c / D) + (coef * b),
                 (d / D) - (coef * a)};
}

/// d vec(C)/d vec(T), cofactor vec(C) = [d, -c, -b, a]. MIRROR of
/// egg.smoothing.metrics._HESS_P and egg.smoothing.batch._HESS_P — any change
/// must be applied to all three copies.
inline constexpr std::array<real, kVecT * kVecT> kHessP = {0.0_r,
                                                           0.0_r,
                                                           0.0_r,
                                                           1.0_r,  //
                                                           0.0_r,
                                                           0.0_r,
                                                           -1.0_r,
                                                           0.0_r,  //
                                                           0.0_r,
                                                           -1.0_r,
                                                           0.0_r,
                                                           0.0_r,  //
                                                           1.0_r,
                                                           0.0_r,
                                                           0.0_r,
                                                           0.0_r};

/// Closed-form Hessian (matches _shape2d_hess_T):
/// H = I/D − (t·cofᵀ + cof·tᵀ)/D² + s·cof·cofᵀ/D³ − s·P/(2D²).
inline Hess mu_hess_closedform(const VecT& t)
{
    const real a = t[0], b = t[1], c = t[2], d = t[3];
    const real D = (a * d) - (b * c);
    const real s = (a * a) + (b * b) + (c * c) + (d * d);
    const std::array<real, kVecT> tv {a, b, c, d};
    const std::array<real, kVecT> cof {d, -c, -b, a};
    const real invD = 1.0_r / D;
    const real invD2 = 1.0_r / (D * D);
    const real sD3 = s / (D * D * D);
    const real s2D2 = s / (2.0_r * D * D);
    Hess H {};
    for (int i = 0; i < kVecT; ++i) {
        for (int j = 0; j < kVecT; ++j) {
            const real eye = (i == j) ? 1.0_r : 0.0_r;
            H[(i * kVecT) + j] = (invD * eye) - (invD2 * ((tv[i] * cof[j]) + (cof[i] * tv[j]))) +
                                 (cof[i] * sD3 * cof[j]) - (s2D2 * kHessP[(i * kVecT) + j]);
        }
    }
    return H;
}

/// Dual-AD gradient (forward mode, one pass with all 4 seeds).
inline Grad mu_grad_dual(const VecT& t)
{
    using Dv = Dual<kVecT>;  // AD over the kVecT components of vec(T)
    const Dv r = mu_shape2d(seed_dual<kVecT>(t[0], 0),
                            seed_dual<kVecT>(t[1], 1),
                            seed_dual<kVecT>(t[2], 2),
                            seed_dual<kVecT>(t[3], 3));
    return Grad {r.g[0], r.g[1], r.g[2], r.g[3]};
}

/// Dual-AD Hessian (second-order forward, one pass).
inline Hess mu_hess_dual(const VecT& t)
{
    using Dv = Dual2<kVecT>;
    const Dv r = mu_shape2d(seed_dual2<kVecT>(t[0], 0),
                            seed_dual2<kVecT>(t[1], 1),
                            seed_dual2<kVecT>(t[2], 2),
                            seed_dual2<kVecT>(t[3], 3));
    Hess H {};
    for (int i = 0; i < kVecT; ++i) {
        for (int j = 0; j < kVecT; ++j) { H[(i * kVecT) + j] = r.h[i][j]; }
    }
    return H;
}

/// δ-continuation untangle surrogate (mirrors metrics._untangle_surrogate):
/// Dh(δ) = ½(D + √(D² + 4δ²)) (> 0 everywhere), μ_δ = s/(2 Dh) − 1. Generic
/// over real / Dual<4> / Dual2<4>, so value/grad/Hess come from one definition.
template <typename T>
inline T mu_untangle(const T& a, const T& b, const T& c, const T& d, real delta)
{
    using sycl::sqrt;  // egg::sqrt for Dual/Dual2 (ADL); sycl::sqrt for real
    const T D = a * d - b * c;
    const T s = a * a + b * b + c * c + d * d;
    const T disc = D * D + T(4.0_r * delta * delta);
    const T Dh = 0.5_r * (D + sqrt(disc));
    return s / (2.0_r * Dh) - 1.0_r;
}

/// Generic scalar shape+size metric (2D), reused for real / Dual<4> / Dual2<4>:
/// mu = (s/(2D))² − 1 + (D − 1)² — the condition-number shape part plus a size
/// term minimal at det T = 1, i.e. cell area = det W. NOT scale-invariant: the
/// target W must carry the desired physical cell size (see
/// egg.smoothing.targets.mean_size_target). Mirrors
/// egg.smoothing.metrics._shape_size_value.
template <typename T> constexpr T mu_shape_size2d(const T& a, const T& b, const T& c, const T& d)
{
    const T D = a * d - b * c;
    const T s = a * a + b * b + c * c + d * d;
    const T dm1 = D - 1.0_r;
    return (s * s) / (4.0_r * D * D) - 1.0_r + dm1 * dm1;
}

inline real mu_ss_value(const VecT& t) { return mu_shape_size2d(t[0], t[1], t[2], t[3]); }

/// Closed-form shape+size gradient (matches _shape_size_value_grad):
/// d(shape)/dT = (s/D²)·T − (s²/(2D³))·C, d(size)/dT = 2(D−1)·C.
inline Grad mu_ss_grad_closedform(const VecT& t)
{
    const real a = t[0], b = t[1], c = t[2], d = t[3];
    const real D = (a * d) - (b * c);
    const real s = (a * a) + (b * b) + (c * c) + (d * d);
    const real coef_s = s / (D * D);
    const real coef_c = ((s * s) / (2.0_r * D * D * D)) - (2.0_r * (D - 1.0_r));
    return Grad {(coef_s * a) - (coef_c * d),
                 (coef_s * b) + (coef_c * c),
                 (coef_s * c) + (coef_c * b),
                 (coef_s * d) - (coef_c * a)};
}

/// Closed-form shape+size Hessian (matches _shape_size_hess_T):
/// H = 2 g_c g_cᵀ + 2(s/2D) H₂ + 2 C Cᵀ + 2(D−1) P, with g_c/H₂ the shape_2d
/// closed forms (s/2D differs from μ₂ by a constant, so its derivatives are
/// mu_grad_closedform / mu_hess_closedform).
inline Hess mu_ss_hess_closedform(const VecT& t)
{
    const real a = t[0], b = t[1], c = t[2], d = t[3];
    const real D = (a * d) - (b * c);
    const real s = (a * a) + (b * b) + (c * c) + (d * d);
    const Grad g = mu_grad_closedform(t);
    const Hess H2 = mu_hess_closedform(t);
    const std::array<real, kVecT> cof {d, -c, -b, a};
    const real cond = s / (2.0_r * D);
    const real dm1 = 2.0_r * (D - 1.0_r);
    Hess H {};
    for (int i = 0; i < kVecT; ++i) {
        for (int j = 0; j < kVecT; ++j) {
            H[(i * kVecT) + j] = (2.0_r * g[i] * g[j]) + (2.0_r * cond * H2[(i * kVecT) + j]) +
                                 (2.0_r * cof[i] * cof[j]) + (dm1 * kHessP[(i * kVecT) + j]);
        }
    }
    return H;
}

// 3D condition-number barrier (generic over real / Dual<9> / Dual2<9>):
// μ_cond = |T|²·|T⁻¹|²/d² − 1 = (Σ tᵢ²)(Σ cofᵢ²)/(9 det²) − 1. Rational in T
// (no fractional powers), so closed form and dual-AD are device-friendly.
// vec(T) row-major. At d=2 it collapses to s²/(4 det²) − 1 (Python _shape_value).
template <typename T> constexpr T det3(const std::array<T, 9>& t)
{
    return (t[0] * ((t[4] * t[8]) - (t[5] * t[7]))) - (t[1] * ((t[3] * t[8]) - (t[5] * t[6]))) +
           (t[2] * ((t[3] * t[7]) - (t[4] * t[6])));
}

/// The 9 cofactors of the 3×3 (row-major; adj = cofᵀ).
template <typename T> constexpr std::array<T, 9> cof3(const std::array<T, 9>& t)
{
    return {(t[4] * t[8]) - (t[5] * t[7]),
            -((t[3] * t[8]) - (t[5] * t[6])),
            (t[3] * t[7]) - (t[4] * t[6]),
            -((t[1] * t[8]) - (t[2] * t[7])),
            (t[0] * t[8]) - (t[2] * t[6]),
            -((t[0] * t[7]) - (t[1] * t[6])),
            (t[1] * t[5]) - (t[2] * t[4]),
            -((t[0] * t[5]) - (t[2] * t[3])),
            (t[0] * t[4]) - (t[1] * t[3])};
}

template <typename T> constexpr T mu_cond3(const std::array<T, 9>& t)
{
    const T D = det3(t);
    const std::array<T, 9> cof = cof3(t);
    T s = T(0.0_r);
    T q = T(0.0_r);
    for (int i = 0; i < 9; ++i) {
        s = s + (t[i] * t[i]);
        q = q + (cof[i] * cof[i]);
    }
    return (s * q) / (9.0_r * D * D) - 1.0_r;
}

/// 3D shape+size: mu_cond3 + (det T − 1)², generic over real / Dual<9> /
/// Dual2<9> (grad/Hess come from AD like the 3D untangle surrogate — no
/// closed-form/jhj fast path yet).
template <typename T> constexpr T mu_cond3_size(const std::array<T, 9>& t)
{
    const T dm1 = det3(t) - T(1.0_r);
    return mu_cond3(t) + dm1 * dm1;
}

/// 3D untangle surrogate: det → Dh = ½(det + √(det² + 4δ²)), mirroring the 2D
/// mu_untangle substitution.
template <typename T> inline T mu_cond3_untangle(const std::array<T, 9>& t, real delta)
{
    using sycl::sqrt;  // egg::sqrt for Dual/Dual2 (ADL); sycl::sqrt for real
    const T D = det3(t);
    const T disc = (D * D) + T(4.0_r * delta * delta);
    const T Dh = 0.5_r * (D + sqrt(disc));
    const std::array<T, 9> cof = cof3(t);
    T s = T(0.0_r);
    T q = T(0.0_r);
    for (int i = 0; i < 9; ++i) {
        s = s + (t[i] * t[i]);
        q = q + (cof[i] * cof[i]);
    }
    return (s * q) / (9.0_r * Dh * Dh) - 1.0_r;
}

/// Closed-form mu_cond3 value/grad/Hess (D=3 production path), generated by
/// scripts/derive_cond3.py (SymPy CSE). Replaces Dual2<9> AD on the GPU hot
/// path — the 729-real AD state clamped VGPRs to 256 and spilled 23 KB of
/// scratch. Parity vs AD ~1e-14 (test_metric_3d.cpp). The AD path stays in
/// mu_cond3/det3/cof3 as parity reference and for UntangleObjectiveT<3>
/// (whose δ-surrogate has a sqrt and is messier to close-form).
struct MuCond3Eval {
    real val;
    real grad[9];
    real hess[81];  // 9x9 row-major, symmetric
};

__attribute__((noinline)) inline MuCond3Eval mu_cond3_eval(const real* t)
{
    MuCond3Eval r;
    // --- Common Subexpressions (SymPy CSE) ---
    const real x0 = ((t[0] * t[0]));
    const real x1 = ((t[1] * t[1]));
    const real x2 = ((t[2] * t[2]));
    const real x3 = ((t[3] * t[3]));
    const real x4 = ((t[4] * t[4]));
    const real x5 = ((t[5] * t[5]));
    const real x6 = ((t[6] * t[6]));
    const real x7 = ((t[7] * t[7]));
    const real x8 = ((t[8] * t[8]));
    const real x9 = x0 + x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8;
    const real x10 = t[4] * t[8];
    const real x11 = t[5] * t[7];
    const real x12 = x10 - x11;
    const real x13 = t[3] * t[7];
    const real x14 = t[4] * t[6];
    const real x15 = x13 - x14;
    const real x16 = t[3] * t[8];
    const real x17 = t[5] * t[6];
    const real x18 = x16 - x17;
    const real x19 = t[0] * x12 - t[1] * x18 + t[2] * x15;
    const real x20 = (1.0_r / (x19 * x19));
    const real x21 = t[0] * t[4];
    const real x22 = t[1] * t[3];
    const real x23 = x21 - x22;
    const real x24 = t[0] * t[5];
    const real x25 = t[2] * t[3] - x24;
    const real x26 = t[0] * t[7];
    const real x27 = t[1] * t[6] - x26;
    const real x28 = t[0] * t[8];
    const real x29 = t[2] * t[6];
    const real x30 = x28 - x29;
    const real x31 = t[1] * t[5];
    const real x32 = t[2] * t[4];
    const real x33 = x31 - x32;
    const real x34 = t[1] * t[8];
    const real x35 = t[2] * t[7] - x34;
    const real x36 = -x18;
    const real x37 = ((x12 * x12)) + ((x15 * x15)) + ((x23 * x23)) + ((x25 * x25)) + ((x27 * x27)) +
                     ((x30 * x30)) + ((x33 * x33)) + ((x35 * x35)) + ((x36 * x36));
    const real x38 = 2 * x23;
    const real x39 = 2 * t[5];
    const real x40 = 2 * x27;
    const real x41 = 2 * t[8];
    const real x42 = t[4] * x38 - t[7] * x40 - x25 * x39 + x30 * x41;
    const real x43 = (1.0_r / 9.0_r) * x9;
    const real x44 = x20 * x43;
    const real x45 = (2.0_r / 9.0_r) * x20 * x37;
    const real inv_x19 = x20 * x19;  // 1/D
    const real x46 = x20 * inv_x19;
    const real x47 = 2 * x10;
    const real x48 = -2 * x11;
    const real x49 = -x47 - x48;
    const real x50 = x46 * x49;
    const real x51 = x37 * x43;
    const real x52 = -t[3] * x38 + 2 * t[5] * x33 + 2 * t[6] * x27 - x35 * x41;
    const real x53 = 2 * x16;
    const real x54 = -2 * x17;
    const real x55 = x53 + x54;
    const real x56 = x46 * x51;
    const real x57 = 2 * x25;
    const real x58 = 2 * x33;
    const real x59 = 2 * t[6];
    const real x60 = 2 * t[7];
    const real x61 = t[3] * x57 - t[4] * x58 - x30 * x59 + x35 * x60;
    const real x62 = 2 * x13;
    const real x63 = -2 * x14;
    const real x64 = -x62 - x63;
    const real x65 = -t[1] * x38 + 2 * t[2] * x25 + 2 * t[7] * x15 - x36 * x41;
    const real x66 = 2 * x34;
    const real x67 = t[2] * t[7];
    const real x68 = -2 * x67;
    const real x69 = x66 + x68;
    const real x70 = t[0] * x38 - t[2] * x58 + x12 * x41 - x15 * x59;
    const real x71 = 2 * x28;
    const real x72 = -2 * x29;
    const real x73 = -x71 - x72;
    const real x74 = -t[0] * x57 + 2 * t[1] * x33 + 2 * t[6] * x36 - x12 * x60;
    const real x75 = 2 * x26;
    const real x76 = t[1] * t[6];
    const real x77 = -2 * x76;
    const real x78 = x75 + x77;
    const real x79 = 2 * t[2];
    const real x80 = t[1] * x40 - 2 * t[4] * x15 - x30 * x79 + x36 * x39;
    const real x81 = 2 * x31;
    const real x82 = -2 * x32;
    const real x83 = -x81 - x82;
    const real x84 = -t[0] * x40 + 2 * t[2] * x35 + 2 * t[3] * x15 - x12 * x39;
    const real x85 = 2 * x24;
    const real x86 = t[2] * t[3];
    const real x87 = -2 * x86;
    const real x88 = x85 + x87;
    const real x89 = 2 * t[1];
    const real x90 = 2 * t[3];
    const real x91 = 2 * t[0] * x30 + 2 * t[4] * x12 - x35 * x89 - x36 * x90;
    const real x92 = 2 * x21;
    const real x93 = -2 * x22;
    const real x94 = -x92 - x93;
    const real x95 = t[0] * x20;
    const real x96 = 2 * x5;
    const real x97 = 2 * x8;
    const real x98 = x96 + x97;
    const real x99 = 2 * x4;
    const real x100 = 2 * x7;
    const real x101 = x100 + x99;
    const real x102 = (2.0_r / 9.0_r) * x42;
    const real x103 = t[0] * x37;
    const real x104 = x51 * x20 * x20;
    const real x105 = x104 * x49;
    const real x106 = t[4] * x90;
    const real x107 = t[7] * x59;
    const real x108 = (2.0_r / 9.0_r) * x95;
    const real x109 = t[1] * x20;
    const real x110 = x46 * x55;
    const real x111 = x42 * x43;
    const real x112 = x43 * x50;
    const real x113 = (2.0_r / 9.0_r) * x103;
    const real x114 = (2.0_r / 9.0_r) * x37;
    const real x115 = x114 * x50;
    const real x116 = 3 * x16 - 3 * x17;
    const real x117 = t[3] * x39;
    const real x118 = t[6] * x41;
    const real x119 = x102 * x20;
    const real x120 = x46 * x64;
    const real x121 = 3 * t[4] * t[6] - 3 * x13;
    const real x122 = t[4] * x89;
    const real x123 = t[2] * x39;
    const real x124 = x46 * x69;
    const real x125 = 3 * x34 - 3 * x67;
    const real x126 = x46 * x73;
    const real x127 = x114 * x46;
    const real x128 = x127 * x9;
    const real x129 = t[8] * x128;
    const real x130 = 3 * t[2] * t[6] - 3 * x28;
    const real x131 = x46 * x78;
    const real x132 = t[7] * x128;
    const real x133 = 3 * x26 - 3 * x76;
    const real x134 = t[1] * x60;
    const real x135 = t[2] * x41;
    const real x136 = x46 * x83;
    const real x137 = 3 * t[2] * t[4] - 3 * x31;
    const real x138 = x46 * x88;
    const real x139 = t[5] * x128;
    const real x140 = 3 * x24 - 3 * x86;
    const real x141 = x46 * x94;
    const real x142 = t[4] * x128;
    const real x143 = 3 * t[1] * t[3] - 3 * x21;
    const real x144 = 2 * x3;
    const real x145 = 2 * x6;
    const real x146 = x144 + x145;
    const real x147 = (2.0_r / 9.0_r) * x52;
    const real x148 = (4.0_r / 9.0_r) * x37;
    const real x149 = x104 * x55;
    const real x150 = t[4] * x39;
    const real x151 = t[7] * x41;
    const real x152 = (2.0_r / 9.0_r) * x109;
    const real x153 = t[2] * x20;
    const real x154 = x43 * x52;
    const real x155 = x110 * x43;
    const real x156 = t[1] * x114;
    const real x157 = x110 * x114;
    const real x158 = x147 * x20;
    const real x159 = t[0] * x90;
    const real x160 = t[1] * x127;
    const real x161 = t[6] * x128;
    const real x162 = t[0] * x59;
    const real x163 = t[3] * x128;
    const real x164 = (2.0_r / 9.0_r) * x61;
    const real x165 = x104 * x64;
    const real x166 = (2.0_r / 9.0_r) * x153;
    const real x167 = t[3] * x20;
    const real x168 = x43 * x61;
    const real x169 = x120 * x43;
    const real x170 = x114 * x124;
    const real x171 = x114 * x120;
    const real x172 = x164 * x20;
    const real x173 = t[2] * x127;
    const real x174 = 2 * x2;
    const real x175 = x174 + x97;
    const real x176 = 2 * x1;
    const real x177 = x100 + x176;
    const real x178 = (2.0_r / 9.0_r) * x65;
    const real x179 = x104 * x69;
    const real x180 = t[0] * x89;
    const real x181 = (2.0_r / 9.0_r) * x167;
    const real x182 = t[4] * x20;
    const real x183 = x43 * x65;
    const real x184 = x124 * x43;
    const real x185 = t[3] * x127;
    const real x186 = t[0] * x79;
    const real x187 = x178 * x20;
    const real x188 = t[4] * x60;
    const real x189 = t[8] * x39;
    const real x190 = t[2] * x128;
    const real x191 = t[1] * x128;
    const real x192 = 2 * x0;
    const real x193 = x145 + x192;
    const real x194 = (2.0_r / 9.0_r) * x70;
    const real x195 = x104 * x73;
    const real x196 = t[1] * x79;
    const real x197 = (2.0_r / 9.0_r) * x182;
    const real x198 = t[5] * x20;
    const real x199 = x43 * x70;
    const real x200 = x126 * x43;
    const real x201 = t[4] * x127;
    const real x202 = x127 * x73;
    const real x203 = x194 * x20;
    const real x204 = t[3] * x59;
    const real x205 = x113 * x46 * x9;
    const real x206 = (2.0_r / 9.0_r) * x74;
    const real x207 = x104 * x78;
    const real x208 = (2.0_r / 9.0_r) * x198;
    const real x209 = t[6] * x20;
    const real x210 = x131 * x43;
    const real x211 = x43 * x74;
    const real x212 = t[5] * x127;
    const real x213 = x127 * x78;
    const real x214 = x20 * x206;
    const real x215 = x174 + x96;
    const real x216 = x176 + x99;
    const real x217 = (2.0_r / 9.0_r) * x80;
    const real x218 = x104 * x83;
    const real x219 = (2.0_r / 9.0_r) * x209;
    const real x220 = t[7] * x20;
    const real x221 = x43 * x80;
    const real x222 = x136 * x43;
    const real x223 = t[6] * x127;
    const real x224 = x127 * x83;
    const real x225 = t[8] * x20;
    const real x226 = x144 + x192;
    const real x227 = (2.0_r / 9.0_r) * x84;
    const real x228 = x104 * x88;
    const real x229 = (2.0_r / 9.0_r) * x91;

    // --- value ---
    r.val = (1.0_r / 9.0_r) * x20 * x37 * x9 - 1;

    // --- gradient (9 entries) ---
    r.grad[0] = t[0] * x45 + x42 * x44 + x50 * x51;
    r.grad[1] = t[1] * x45 + x44 * x52 + x55 * x56;
    r.grad[2] = t[2] * x45 + x44 * x61 + x56 * x64;
    r.grad[3] = t[3] * x45 + x44 * x65 + x56 * x69;
    r.grad[4] = t[4] * x45 + x44 * x70 + x56 * x73;
    r.grad[5] = t[5] * x45 + x44 * x74 + x56 * x78;
    r.grad[6] = t[6] * x45 + x44 * x80 + x56 * x83;
    r.grad[7] = t[7] * x45 + x44 * x84 + x56 * x88;
    r.grad[8] = t[8] * x45 + x44 * x91 + x56 * x94;

    // --- symmetric Hessian (45 unique entries) ---
    r.hess[0] = x102 * x50 * x9 + (4.0_r / 9.0_r) * x103 * x50 +
                x105 * (3 * t[5] * t[7] - 3 * x10) + (4.0_r / 9.0_r) * x42 * x95 +
                x44 * (x101 + x98) + x45;
    r.hess[1] = r.hess[9] = t[1] * x115 + x102 * x109 + x105 * x116 + x108 * x52 + x110 * x111 +
                            x110 * x113 + x112 * x52 + x44 * (-x106 - x107);
    r.hess[2] = r.hess[18] = t[2] * x115 + t[2] * x119 + x105 * x121 + x108 * x61 + x111 * x120 +
                             x112 * x61 + x113 * x120 + x44 * (-x117 - x118);
    r.hess[3] = r.hess[27] = t[3] * x115 + t[3] * x119 + x105 * x125 + x108 * x65 + x111 * x124 +
                             x112 * x65 + x113 * x124 + x44 * (-x122 - x123);
    r.hess[4] = r.hess[36] = t[4] * x115 + t[4] * x119 + x105 * x130 + x108 * x70 + x111 * x126 +
                             x112 * x70 + x113 * x126 - x129 + x44 * (4 * x21 + x93);
    r.hess[5] = r.hess[45] = t[5] * x115 + t[5] * x119 + x105 * x133 + x108 * x74 + x111 * x131 +
                             x112 * x74 + x113 * x131 + x132 + x44 * (4 * x24 + x87);
    r.hess[6] = r.hess[54] = t[6] * x115 + t[6] * x119 + x105 * x137 + x108 * x80 + x111 * x136 +
                             x112 * x80 + x113 * x136 + x44 * (-x134 - x135);
    r.hess[7] = r.hess[63] = t[7] * x115 + t[7] * x119 + x105 * x140 + x108 * x84 + x111 * x138 +
                             x112 * x84 + x113 * x138 + x139 + x44 * (4 * x26 + x77);
    r.hess[8] = r.hess[72] = t[8] * x115 + t[8] * x119 + x105 * x143 + x108 * x91 + x111 * x141 +
                             x112 * x91 + x113 * x141 - x142 + x44 * (4 * x28 + x72);
    r.hess[10] = t[1] * x110 * x148 + (4.0_r / 9.0_r) * x109 * x52 + x110 * x147 * x9 +
                 x116 * x149 + x44 * (x146 + x98) + x45;
    r.hess[11] = r.hess[19] = t[2] * x157 + x120 * x154 + x120 * x156 + x121 * x149 + x147 * x153 +
                              x152 * x61 + x155 * x61 + x44 * (-x150 - x151);
    r.hess[12] = r.hess[28] = t[3] * x157 + t[3] * x158 + x124 * x154 + x124 * x156 + x125 * x149 +
                              x129 + x152 * x65 + x155 * x65 + x44 * (4 * t[1] * t[3] - x92);
    r.hess[13] = r.hess[37] = t[4] * x157 + t[4] * x158 + x126 * x154 + x130 * x149 + x152 * x70 +
                              x155 * x70 + x160 * x73 + x44 * (-x123 - x159);
    r.hess[14] = r.hess[46] = t[5] * x157 + t[5] * x158 + x131 * x154 + x133 * x149 + x152 * x74 +
                              x155 * x74 + x160 * x78 - x161 + x44 * (4 * x31 + x82);
    r.hess[15] = r.hess[55] = t[6] * x157 + t[6] * x158 + x136 * x154 + x137 * x149 - x139 +
                              x152 * x80 + x155 * x80 + x160 * x83 + x44 * (4 * t[1] * t[6] - x75);
    r.hess[16] = r.hess[64] = t[7] * x157 + t[7] * x158 + x138 * x154 + x140 * x149 + x152 * x84 +
                              x155 * x84 + x160 * x88 + x44 * (-x135 - x162);
    r.hess[17] = r.hess[73] = t[8] * x157 + t[8] * x158 + x141 * x154 + x143 * x149 + x152 * x91 +
                              x155 * x91 + x160 * x94 + x163 + x44 * (4 * x34 + x68);
    r.hess[20] = t[2] * x120 * x148 + x120 * x164 * x9 + x121 * x165 +
                 (4.0_r / 9.0_r) * x153 * x61 + x44 * (x101 + x146) + x45;
    r.hess[21] = r.hess[29] = t[2] * x170 + t[3] * x171 + x124 * x168 + x125 * x165 - x132 +
                              x164 * x167 + x166 * x65 + x169 * x65 + x44 * (4 * t[2] * t[3] - x85);
    r.hess[22] = r.hess[38] = t[4] * x171 + t[4] * x172 + x126 * x168 + x130 * x165 + x161 +
                              x166 * x70 + x169 * x70 + x173 * x73 + x44 * (4 * t[2] * t[4] - x81);
    r.hess[23] = r.hess[47] = t[5] * x171 + t[5] * x172 + x131 * x168 + x133 * x165 + x166 * x74 +
                              x169 * x74 + x173 * x78 + x44 * (-x122 - x159);
    r.hess[24] = r.hess[56] = t[6] * x171 + t[6] * x172 + x136 * x168 + x137 * x165 + x142 +
                              x166 * x80 + x169 * x80 + x173 * x83 + x44 * (4 * t[2] * t[6] - x71);
    r.hess[25] = r.hess[65] = t[7] * x171 + t[7] * x172 + x138 * x168 + x140 * x165 - x163 +
                              x166 * x84 + x169 * x84 + x173 * x88 + x44 * (4 * t[2] * t[7] - x66);
    r.hess[26] = r.hess[74] = t[8] * x171 + t[8] * x172 + x141 * x168 + x143 * x165 + x166 * x91 +
                              x169 * x91 + x173 * x94 + x44 * (-x134 - x162);
    r.hess[30] = t[3] * x124 * x148 + x124 * x178 * x9 + x125 * x179 +
                 (4.0_r / 9.0_r) * x167 * x65 + x44 * (x175 + x177) + x45;
    r.hess[31] = r.hess[39] = t[4] * x170 + x126 * x183 + x130 * x179 + x178 * x182 + x181 * x70 +
                              x184 * x70 + x185 * x73 + x44 * (-x107 - x180);
    r.hess[32] = r.hess[48] = t[5] * x170 + t[5] * x187 + x131 * x183 + x133 * x179 + x181 * x74 +
                              x184 * x74 + x185 * x78 + x44 * (-x118 - x186);
    r.hess[33] = r.hess[57] = t[6] * x170 + t[6] * x187 + x136 * x183 + x137 * x179 + x181 * x80 +
                              x184 * x80 + x185 * x83 + x44 * (-x188 - x189);
    r.hess[34] = r.hess[66] = t[7] * x170 + t[7] * x187 + x138 * x183 + x140 * x179 + x181 * x84 +
                              x184 * x84 + x185 * x88 - x190 + x44 * (4 * x13 + x63);
    r.hess[35] = r.hess[75] = t[8] * x170 + t[8] * x187 + x141 * x183 + x143 * x179 + x181 * x91 +
                              x184 * x91 + x185 * x94 + x191 + x44 * (4 * x16 + x54);
    r.hess[40] = t[4] * x126 * x148 + x126 * x194 * x9 + x130 * x195 +
                 (4.0_r / 9.0_r) * x182 * x70 + x44 * (x175 + x193) + x45;
    r.hess[41] = r.hess[49] = t[5] * x202 + x131 * x199 + x133 * x195 + x194 * x198 + x197 * x74 +
                              x200 * x74 + x201 * x78 + x44 * (-x151 - x196);
    r.hess[42] = r.hess[58] = t[6] * x202 + t[6] * x203 + x136 * x199 + x137 * x195 + x190 +
                              x197 * x80 + x200 * x80 + x201 * x83 + x44 * (4 * t[4] * t[6] - x62);
    r.hess[43] = r.hess[67] = t[7] * x202 + t[7] * x203 + x138 * x199 + x140 * x195 + x197 * x84 +
                              x200 * x84 + x201 * x88 + x44 * (-x189 - x204);
    r.hess[44] = r.hess[76] = t[8] * x202 + t[8] * x203 + x141 * x199 + x143 * x195 + x197 * x91 +
                              x200 * x91 + x201 * x94 - x205 + x44 * (4 * x10 + x48);
    r.hess[50] = t[5] * x131 * x148 + x131 * x206 * x9 + x133 * x207 +
                 (4.0_r / 9.0_r) * x198 * x74 + x44 * (x177 + x193) + x45;
    r.hess[51] = r.hess[59] = t[6] * x213 + x136 * x211 + x137 * x207 - x191 + x206 * x209 +
                              x208 * x80 + x210 * x80 + x212 * x83 + x44 * (4 * t[5] * t[6] - x53);
    r.hess[52] = r.hess[68] = t[7] * x213 + t[7] * x214 + x138 * x211 + x140 * x207 + x205 +
                              x208 * x84 + x210 * x84 + x212 * x88 + x44 * (4 * t[5] * t[7] - x47);
    r.hess[53] = r.hess[77] = t[8] * x213 + t[8] * x214 + x141 * x211 + x143 * x207 + x208 * x91 +
                              x210 * x91 + x212 * x94 + x44 * (-x188 - x204);
    r.hess[60] = t[6] * x136 * x148 + x136 * x217 * x9 + x137 * x218 +
                 (4.0_r / 9.0_r) * x209 * x80 + x44 * (x215 + x216) + x45;
    r.hess[61] = r.hess[69] = t[7] * x224 + x138 * x221 + x140 * x218 + x217 * x220 + x219 * x84 +
                              x222 * x84 + x223 * x88 + x44 * (-x106 - x180);
    r.hess[62] = r.hess[78] = t[8] * x224 + x141 * x221 + x143 * x218 + x217 * x225 + x219 * x91 +
                              x222 * x91 + x223 * x94 + x44 * (-x117 - x186);
    r.hess[70] = t[7] * x138 * x148 + x138 * x227 * x9 + x140 * x228 +
                 (4.0_r / 9.0_r) * x220 * x84 + x44 * (x215 + x226) + x45;
    r.hess[71] = r.hess[79] = t[7] * x127 * x94 + t[8] * x127 * x88 + x138 * x43 * x91 +
                              x141 * x43 * x84 + x143 * x228 + x220 * x229 + x225 * x227 +
                              x44 * (-x150 - x196);
    r.hess[80] = t[8] * x141 * x148 + x104 * x143 * x94 + x141 * x229 * x9 +
                 (4.0_r / 9.0_r) * x225 * x91 + x44 * (x216 + x226) + x45;

    return r;
}

/// mu''(t; w): 2nd directional derivative of mu_cond3 at t along the 9-vector
/// w, used by mu_cond3_jhj's polarization. cof[9] and s=Σtᵢ², q=Σcofᵢ², D=det
/// are precomputed once by the caller and shared across all 6 directions, so
/// this body is only the cheap w-contractions. mu = f − 1, f = s q/(9 D²);
/// returns f''. Verified vs wᵀHw to ~7e-13 (derive_cond3.py).
__attribute__((noinline)) inline real
  mu_cond3_d2dir(const real* t, const real* cof, real s, real q, real D, const real* w)
{
    // Cofactor directional derivatives. Index map (a,b,c,d) per i:
    //  0:(4,8,5,7) 1:(5,6,3,8) 2:(3,7,4,6) 3:(2,7,1,8) 4:(0,8,2,6)
    //  5:(1,6,0,7) 6:(1,5,2,4) 7:(2,3,0,5) 8:(0,4,1,3)
    const real cp0 = (w[4] * t[8]) + (t[4] * w[8]) - (w[5] * t[7]) - (t[5] * w[7]);
    const real cp1 = (w[5] * t[6]) + (t[5] * w[6]) - (w[3] * t[8]) - (t[3] * w[8]);
    const real cp2 = (w[3] * t[7]) + (t[3] * w[7]) - (w[4] * t[6]) - (t[4] * w[6]);
    const real cp3 = (w[2] * t[7]) + (t[2] * w[7]) - (w[1] * t[8]) - (t[1] * w[8]);
    const real cp4 = (w[0] * t[8]) + (t[0] * w[8]) - (w[2] * t[6]) - (t[2] * w[6]);
    const real cp5 = (w[1] * t[6]) + (t[1] * w[6]) - (w[0] * t[7]) - (t[0] * w[7]);
    const real cp6 = (w[1] * t[5]) + (t[1] * w[5]) - (w[2] * t[4]) - (t[2] * w[4]);
    const real cp7 = (w[2] * t[3]) + (t[2] * w[3]) - (w[0] * t[5]) - (t[0] * w[5]);
    const real cp8 = (w[0] * t[4]) + (t[0] * w[4]) - (w[1] * t[3]) - (t[1] * w[3]);
    const real cpp0 = 2.0_r * ((w[4] * w[8]) - (w[5] * w[7]));
    const real cpp1 = 2.0_r * ((w[5] * w[6]) - (w[3] * w[8]));
    const real cpp2 = 2.0_r * ((w[3] * w[7]) - (w[4] * w[6]));
    const real cpp3 = 2.0_r * ((w[2] * w[7]) - (w[1] * w[8]));
    const real cpp4 = 2.0_r * ((w[0] * w[8]) - (w[2] * w[6]));
    const real cpp5 = 2.0_r * ((w[1] * w[6]) - (w[0] * w[7]));
    const real cpp6 = 2.0_r * ((w[1] * w[5]) - (w[2] * w[4]));
    const real cpp7 = 2.0_r * ((w[2] * w[3]) - (w[0] * w[5]));
    const real cpp8 = 2.0_r * ((w[0] * w[4]) - (w[1] * w[3]));

    // Directional 1st/2nd derivatives of the building blocks s, D, q along w.
    const real sp =
      2.0_r * ((t[0] * w[0]) + (t[1] * w[1]) + (t[2] * w[2]) + (t[3] * w[3]) + (t[4] * w[4]) +
               (t[5] * w[5]) + (t[6] * w[6]) + (t[7] * w[7]) + (t[8] * w[8]));
    const real spp =
      2.0_r * ((w[0] * w[0]) + (w[1] * w[1]) + (w[2] * w[2]) + (w[3] * w[3]) + (w[4] * w[4]) +
               (w[5] * w[5]) + (w[6] * w[6]) + (w[7] * w[7]) + (w[8] * w[8]));
    const real Dp = (w[0] * cof[0]) + (w[1] * cof[1]) + (w[2] * cof[2]) + (w[3] * cof[3]) +
                    (w[4] * cof[4]) + (w[5] * cof[5]) + (w[6] * cof[6]) + (w[7] * cof[7]) +
                    (w[8] * cof[8]);
    const real Dpp = (w[0] * cp0) + (w[1] * cp1) + (w[2] * cp2) + (w[3] * cp3) + (w[4] * cp4) +
                     (w[5] * cp5) + (w[6] * cp6) + (w[7] * cp7) + (w[8] * cp8);
    const real qp =
      2.0_r * ((cof[0] * cp0) + (cof[1] * cp1) + (cof[2] * cp2) + (cof[3] * cp3) + (cof[4] * cp4) +
               (cof[5] * cp5) + (cof[6] * cp6) + (cof[7] * cp7) + (cof[8] * cp8));
    const real qpp =
      2.0_r * ((cp0 * cp0) + (cp1 * cp1) + (cp2 * cp2) + (cp3 * cp3) + (cp4 * cp4) + (cp5 * cp5) +
               (cp6 * cp6) + (cp7 * cp7) + (cp8 * cp8) + (cof[0] * cpp0) + (cof[1] * cpp1) +
               (cof[2] * cpp2) + (cof[3] * cpp3) + (cof[4] * cpp4) + (cof[5] * cpp5) +
               (cof[6] * cpp6) + (cof[7] * cpp7) + (cof[8] * cpp8));

    // f = s q / (9 D²); D2 = f'' via the product/quotient rule on g = s q, h = 9 D².
    const real h = 9.0_r * D * D;
    const real invh = 1.0_r / h;
    const real hp = 18.0_r * D * Dp;
    const real hpp = 18.0_r * ((Dp * Dp) + (D * Dpp));
    const real g = s * q;
    const real gp = (sp * q) + (s * qp);
    const real gpp = (spp * q) + (2.0_r * sp * qp) + (s * qpp);
    return (gpp * invh) - (2.0_r * gp * hp * invh * invh) - (g * hpp * invh * invh) +
           (2.0_r * g * hp * hp * invh * invh * invh);
}

/// Value + gradient of mu_cond3 at t, written to memory (pool dies here).
__attribute__((noinline)) inline void mu_cond3_valgrad(const real* t, real* val_out, real* grad_out)
{
    // --- Common Subexpressions (SymPy CSE) ---
    const real x0 = ((t[0] * t[0])) + ((t[1] * t[1])) + ((t[2] * t[2])) + ((t[3] * t[3])) +
                    ((t[4] * t[4])) + ((t[5] * t[5])) + ((t[6] * t[6])) + ((t[7] * t[7])) +
                    ((t[8] * t[8]));
    const real x1 = t[4] * t[8];
    const real x2 = -t[5] * t[7] + x1;
    const real x3 = t[3] * t[7];
    const real x4 = -t[4] * t[6] + x3;
    const real x5 = t[3] * t[8];
    const real x6 = t[5] * t[6];
    const real x7 = x5 - x6;
    const real x8 = t[0] * x2 - t[1] * x7 + t[2] * x4;
    const real x9 = (1.0_r / (x8 * x8));
    const real x10 = t[0] * t[4];
    const real x11 = -t[1] * t[3] + x10;
    const real x12 = t[0] * t[5];
    const real x13 = t[2] * t[3] - x12;
    const real x14 = t[0] * t[7];
    const real x15 = t[1] * t[6] - x14;
    const real x16 = t[0] * t[8];
    const real x17 = -t[2] * t[6] + x16;
    const real x18 = t[1] * t[5];
    const real x19 = -t[2] * t[4] + x18;
    const real x20 = t[1] * t[8];
    const real x21 = t[2] * t[7] - x20;
    const real x22 = -x7;
    const real x23 = ((x11 * x11)) + ((x13 * x13)) + ((x15 * x15)) + ((x17 * x17)) + ((x19 * x19)) +
                     ((x2 * x2)) + ((x21 * x21)) + ((x22 * x22)) + ((x4 * x4));
    const real x24 = 2 * x11;
    const real x25 = 2 * t[5];
    const real x26 = 2 * x15;
    const real x27 = 2 * t[8];
    const real x28 = (1.0_r / 9.0_r) * x0;
    const real x29 = x28 * x9;
    const real x30 = (2.0_r / 9.0_r) * x23 * x9;
    const real x31 = x23 * x28 / (((x8 * x8) * x8));
    const real x32 = 2 * x13;
    const real x33 = 2 * x19;
    const real x34 = 2 * t[6];
    const real x35 = 2 * t[7];

    *val_out = (1.0_r / 9.0_r) * x0 * x23 * x9 - 1;
    grad_out[0] = t[0] * x30 + x29 * (t[4] * x24 - t[7] * x26 - x13 * x25 + x17 * x27) +
                  x31 * (2 * t[5] * t[7] - 2 * x1);
    grad_out[1] = t[1] * x30 + x29 * (-t[3] * x24 + 2 * t[5] * x19 + 2 * t[6] * x15 - x21 * x27) +
                  x31 * (2 * x5 - 2 * x6);
    grad_out[2] = t[2] * x30 + x29 * (t[3] * x32 - t[4] * x33 - x17 * x34 + x21 * x35) +
                  x31 * (2 * t[4] * t[6] - 2 * x3);
    grad_out[3] = t[3] * x30 + x29 * (-t[1] * x24 + 2 * t[2] * x13 + 2 * t[7] * x4 - x22 * x27) +
                  x31 * (-2 * t[2] * t[7] + 2 * x20);
    grad_out[4] = t[4] * x30 + x29 * (t[0] * x24 - t[2] * x33 + x2 * x27 - x34 * x4) +
                  x31 * (2 * t[2] * t[6] - 2 * x16);
    grad_out[5] = t[5] * x30 + x29 * (-t[0] * x32 + 2 * t[1] * x19 + 2 * t[6] * x22 - x2 * x35) +
                  x31 * (-2 * t[1] * t[6] + 2 * x14);
    grad_out[6] = t[6] * x30 + x29 * (t[1] * x26 - 2 * t[2] * x17 - 2 * t[4] * x4 + x22 * x25) +
                  x31 * (2 * t[2] * t[4] - 2 * x18);
    grad_out[7] = t[7] * x30 + x29 * (-t[0] * x26 + 2 * t[2] * x21 + 2 * t[3] * x4 - x2 * x25) +
                  x31 * (-2 * t[2] * t[3] + 2 * x12);
    grad_out[8] = t[8] * x30 +
                  x29 * (2 * t[0] * x17 - 2 * t[1] * x21 - 2 * t[3] * x22 + 2 * t[4] * x2) +
                  x31 * (2 * t[1] * t[3] - 2 * x10);
}

/// Fused value + gradient + contracted Hessian jhj = Jbᵀ H Jb (3×3 row-major)
/// via 6 directional 2nd derivatives + polarization; never forms the 81-entry
/// Hessian. Jb is the runtime 9×3 row-major chain matrix (column i = vᵢ).
/// cof/s/q/D are computed once and shared by the 6 mu_cond3_d2dir calls.
__attribute__((noinline)) inline void
  mu_cond3_jhj(const real* t, const real* Jb, real* val_out, real* grad_out, real* jhj_out)
{
    mu_cond3_valgrad(t, val_out, grad_out);

    // Shared building blocks (computed once, reused for all 6 polarization dirs).
    real cof[9];
    cof[0] = (t[4] * t[8]) - (t[5] * t[7]);
    cof[1] = (t[5] * t[6]) - (t[3] * t[8]);
    cof[2] = (t[3] * t[7]) - (t[4] * t[6]);
    cof[3] = (t[2] * t[7]) - (t[1] * t[8]);
    cof[4] = (t[0] * t[8]) - (t[2] * t[6]);
    cof[5] = (t[1] * t[6]) - (t[0] * t[7]);
    cof[6] = (t[1] * t[5]) - (t[2] * t[4]);
    cof[7] = (t[2] * t[3]) - (t[0] * t[5]);
    cof[8] = (t[0] * t[4]) - (t[1] * t[3]);
    const real s = (t[0] * t[0]) + (t[1] * t[1]) + (t[2] * t[2]) + (t[3] * t[3]) + (t[4] * t[4]) +
                   (t[5] * t[5]) + (t[6] * t[6]) + (t[7] * t[7]) + (t[8] * t[8]);
    const real q = (cof[0] * cof[0]) + (cof[1] * cof[1]) + (cof[2] * cof[2]) + (cof[3] * cof[3]) +
                   (cof[4] * cof[4]) + (cof[5] * cof[5]) + (cof[6] * cof[6]) + (cof[7] * cof[7]) +
                   (cof[8] * cof[8]);
    const real D = (t[0] * cof[0]) + (t[1] * cof[1]) + (t[2] * cof[2]);

    // The 3 columns of Jb are the polarization directions v0, v1, v2.
    real v0[9], v1[9], v2[9];
    for (int k = 0; k < 9; ++k) {
        v0[k] = Jb[(k * 3) + 0];
        v1[k] = Jb[(k * 3) + 1];
        v2[k] = Jb[(k * 3) + 2];
    }
    const real d00 = mu_cond3_d2dir(t, cof, s, q, D, v0);
    const real d11 = mu_cond3_d2dir(t, cof, s, q, D, v1);
    const real d22 = mu_cond3_d2dir(t, cof, s, q, D, v2);

    // Off-diagonals by polarization; reuse one scratch direction (low liveness).
    real w[9];
    for (int k = 0; k < 9; ++k) { w[k] = v0[k] + v1[k]; }
    const real j01 = 0.5_r * (mu_cond3_d2dir(t, cof, s, q, D, w) - d00 - d11);
    for (int k = 0; k < 9; ++k) { w[k] = v0[k] + v2[k]; }
    const real j02 = 0.5_r * (mu_cond3_d2dir(t, cof, s, q, D, w) - d00 - d22);
    for (int k = 0; k < 9; ++k) { w[k] = v1[k] + v2[k]; }
    const real j12 = 0.5_r * (mu_cond3_d2dir(t, cof, s, q, D, w) - d11 - d22);

    jhj_out[0] = d00;
    jhj_out[1] = j01;
    jhj_out[2] = j02;
    jhj_out[3] = j01;
    jhj_out[4] = d11;
    jhj_out[5] = j12;
    jhj_out[6] = j02;
    jhj_out[7] = j12;
    jhj_out[8] = d22;
}

/// Objective concept: per-sample μ value/grad/Hess w.r.t. vec(T) (E = Σμ is
/// accumulated by the kernels) plus the line-search accept policy on min det A.
/// The kinds are a closed set in a std::variant, dispatched once per run with
/// std::visit to instantiate a monomorphic kernel — no virtuals, no per-DOF
/// type dispatch on device.
template <class M, int D>
concept ObjectiveD = requires(const M& m, const VecTN<D>& t, real det) {
    { m.value(t) } -> std::convertible_to<real>;
    { m.grad(t) } -> std::convertible_to<GradN<D>>;
    { m.hess(t) } -> std::convertible_to<HessN<D>>;
    // Line-search accept test on min det A for this objective's regime.
    { m.accept_mindet(det) } -> std::convertible_to<bool>;
};

/// Barrier shape objective. D=2: the classic shape_2d closed forms
/// (bit-identical production path); D=3: the condition-number barrier
/// mu_cond3 via its generated closed forms.
template <int D> struct ShapeObjectiveT {
    static_assert(D == 2 || D == 3, "ShapeObjectiveT: unsupported dimension");
    static constexpr int kN = dim::vecT(D);

    [[nodiscard]] real value(const VecTN<D>& t) const
    {
        if constexpr (D == 2) {
            return mu_value(t);
        } else {
            return mu_cond3(t);
        }
    }
    [[nodiscard]] GradN<D> grad(const VecTN<D>& t) const
    {
        if constexpr (D == 2) {
            return mu_grad_closedform(t);
        } else {
            MuCond3Eval r = mu_cond3_eval(t.data());
            GradN<D> g;
            for (int i = 0; i < kN; ++i) { g[i] = r.grad[i]; }
            return g;
        }
    }
    [[nodiscard]] HessN<D> hess(const VecTN<D>& t) const
    {
        if constexpr (D == 2) {
            return mu_hess_closedform(t);
        } else {
            MuCond3Eval r = mu_cond3_eval(t.data());
            HessN<D> H {};
            for (int i = 0; i < 81; ++i) { H[i] = r.hess[i]; }
            return H;
        }
    }
    /// Fused value + gradient + contracted Hessian jhj = Jbᵀ H Jb (D=3 only):
    /// the patch hot path's single metric entry point — one CSE pass, never
    /// materialises the 81-entry Hessian. @p Jb is the runtime 9×3 chain
    /// matrix (role-selected J columns); @p val / @p grad / @p jhj out-params.
    void eval_jhj(const VecTN<D>& t, const real* Jb, real* val, real* grad, real* jhj) const
        requires(D == 3)
    { mu_cond3_jhj(t.data(), Jb, val, grad, jhj); }
    /// Barrier: a step is only valid if every cell stays positively oriented.
    [[nodiscard]] bool accept_mindet(real mindet) const { return mindet > 0.0_r; }
};

/// Barrier shape+size objective: the shape barrier plus (det T − 1)², so cells
/// are also pushed toward the target size det W (size-aware — the target must
/// carry physical scale). D=2: closed forms mirroring the NumPy oracle's
/// "shape_size"; D=3: mu_cond3_size via dual AD (no fused jhj path — patch.hpp
/// takes its generic branch).
template <int D> struct ShapeSizeObjectiveT {
    static_assert(D == 2 || D == 3, "ShapeSizeObjectiveT: unsupported dimension");
    static constexpr int kN = dim::vecT(D);

    [[nodiscard]] real value(const VecTN<D>& t) const
    {
        if constexpr (D == 2) {
            return mu_ss_value(t);
        } else {
            return mu_cond3_size(t);
        }
    }
    [[nodiscard]] GradN<D> grad(const VecTN<D>& t) const
    {
        if constexpr (D == 2) {
            return mu_ss_grad_closedform(t);
        } else {
            std::array<Dual<kN>, kN> td;
            for (int i = 0; i < kN; ++i) { td[i] = seed_dual<kN>(t[i], i); }
            const Dual<kN> r = mu_cond3_size(td);
            GradN<D> g;
            for (int i = 0; i < kN; ++i) { g[i] = r.g[i]; }
            return g;
        }
    }
    [[nodiscard]] HessN<D> hess(const VecTN<D>& t) const
    {
        if constexpr (D == 2) {
            return mu_ss_hess_closedform(t);
        } else {
            std::array<Dual2<kN>, kN> td;
            for (int i = 0; i < kN; ++i) { td[i] = seed_dual2<kN>(t[i], i); }
            const Dual2<kN> r = mu_cond3_size(td);
            HessN<D> H {};
            for (int i = 0; i < kN; ++i) {
                for (int j = 0; j < kN; ++j) { H[(i * kN) + j] = r.h[i][j]; }
            }
            return H;
        }
    }
    /// Barrier: a step is only valid if every cell stays positively oriented.
    [[nodiscard]] bool accept_mindet(real mindet) const { return mindet > 0.0_r; }
};

/// δ-continuation untangle objective: surrogate value + dual-AD grad/Hess and
/// the relaxed accept rule (the surrogate is finite on folded cells, so
/// min det A may be ≤ 0 during continuation).
template <int D> struct UntangleObjectiveT {
    static_assert(D == 2 || D == 3, "UntangleObjectiveT: unsupported dimension");
    static constexpr int kN = dim::vecT(D);
    real delta {0.0_r};

    [[nodiscard]] real value(const VecTN<D>& t) const
    {
        if constexpr (D == 2) {
            return mu_untangle(t[0], t[1], t[2], t[3], delta);
        } else {
            return mu_cond3_untangle(t, delta);
        }
    }
    [[nodiscard]] GradN<D> grad(const VecTN<D>& t) const
    {
        if constexpr (D == 2) {
            using Dv = Dual<kVecT>;
            const Dv r = mu_untangle(seed_dual<kVecT>(t[0], 0),
                                     seed_dual<kVecT>(t[1], 1),
                                     seed_dual<kVecT>(t[2], 2),
                                     seed_dual<kVecT>(t[3], 3),
                                     delta);
            return GradN<D> {r.g[0], r.g[1], r.g[2], r.g[3]};
        } else {
            std::array<Dual<kN>, kN> td;
            for (int i = 0; i < kN; ++i) { td[i] = seed_dual<kN>(t[i], i); }
            const Dual<kN> r = mu_cond3_untangle(td, delta);
            GradN<D> g;
            for (int i = 0; i < kN; ++i) { g[i] = r.g[i]; }
            return g;
        }
    }
    [[nodiscard]] HessN<D> hess(const VecTN<D>& t) const
    {
        if constexpr (D == 2) {
            using Dv = Dual2<kVecT>;
            const Dv r = mu_untangle(seed_dual2<kVecT>(t[0], 0),
                                     seed_dual2<kVecT>(t[1], 1),
                                     seed_dual2<kVecT>(t[2], 2),
                                     seed_dual2<kVecT>(t[3], 3),
                                     delta);
            HessN<D> H {};
            for (int i = 0; i < kVecT; ++i) {
                for (int j = 0; j < kVecT; ++j) { H[(i * kVecT) + j] = r.h[i][j]; }
            }
            return H;
        } else {
            std::array<Dual2<kN>, kN> td;
            for (int i = 0; i < kN; ++i) { td[i] = seed_dual2<kN>(t[i], i); }
            const Dual2<kN> r = mu_cond3_untangle(td, delta);
            HessN<D> H {};
            for (int i = 0; i < kN; ++i) {
                for (int j = 0; j < kN; ++j) { H[(i * kN) + j] = r.h[i][j]; }
            }
            return H;
        }
    }
    [[nodiscard]] bool accept_mindet(real) const { return true; }
};

/// Closed set of objective kinds for std::visit dispatch.
template <int D>
using ObjectiveKindT =
  std::variant<ShapeObjectiveT<D>, UntangleObjectiveT<D>, ShapeSizeObjectiveT<D>>;

/// Objective for a run: "untangle" -> δ-surrogate, "shape_size" -> shape+size,
/// else the shape barrier.
template <int D = kDefaultDim>
inline ObjectiveKindT<D> make_objective(std::string_view phase, real delta)
{
    if (phase == "untangle") { return UntangleObjectiveT<D> {delta}; }
    if (phase == "shape_size") { return ShapeSizeObjectiveT<D> {}; }
    return ShapeObjectiveT<D> {};
}

// D=2 legacy aliases for the oracle surface and existing call sites.
using ShapeObjective = ShapeObjectiveT<2>;
using ShapeSizeObjective = ShapeSizeObjectiveT<2>;
using UntangleObjective = UntangleObjectiveT<2>;
using ObjectiveKind = ObjectiveKindT<2>;

template <class M>
concept Objective = ObjectiveD<M, 2>;

static_assert(Objective<ShapeObjective>);
static_assert(Objective<ShapeSizeObjective>);
static_assert(Objective<UntangleObjective>);

}  // namespace egg
